import type { ExerciseDef } from '../types.js';

// MET: 2024 Adult Compendium (Herrmann 2024 J Sport Health Sci, doi:10.1016/j.jshs.2023.10.010; codes at pacompendium.com).

export const CALISTHENICS: ExerciseDef[] = [
  {
    id: 'push-up',
    name: 'Push-up',
    category: 'calisthenics',
    icon: '💪',
    mode: 'reps',
    camera: 'side',
    difficulty: 2,
    equipment: [],
    muscles: ['chest', 'triceps', 'front delts', 'core'],
    summary: 'Classic horizontal press lowering a rigid plank until the elbows reach about 90 degrees.',
    setup: [
      'Place the camera at floor height, 2–3 m to your side.',
      'Hands under shoulders, legs straight, body in one line.',
      'Keep your whole body in frame from head to feet.',
    ],
    met: 3.8, // 02022 calisthenics, moderate
    angles: [
      { id: 'elbow', label: 'Elbow', kind: 'joint', joint: 'elbow' },
      { id: 'bodyLine', label: 'Body line', kind: 'joint', joint: 'bodyLine' },
      { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee' },
    ],
    checks: [
      { angle: 'elbow', when: 'bottom', good: [50, 95], ok: [45, 115], cue: 'Lower your chest closer to the floor', why: 'Reaching ~90° elbow flexion loads the pectorals and triceps through their full working range.', weight: 2 },
      { angle: 'bodyLine', when: 'active', good: [165, 180], ok: [155, 180], cue: 'Brace your core, keep hips in line', why: 'Hip sag or pike shifts load off the chest and stresses the lumbar spine.', weight: 2 },
      { angle: 'knee', when: 'any', good: [160, 180], ok: [150, 180], cue: 'Keep your legs straight', why: 'Bent knees shorten the lever and indicate a loss of full-body tension.' },
    ],
    reps: { driver: 'elbow', start: 'high', enter: 150, exit: 165, target: 95 },
  },
  {
    id: 'knee-push-up',
    name: 'Knee Push-up',
    category: 'calisthenics',
    icon: '🙌',
    mode: 'reps',
    camera: 'side',
    difficulty: 1,
    equipment: ['mat'],
    muscles: ['chest', 'triceps', 'front delts'],
    summary: 'Regressed push-up from the knees that keeps a straight line from shoulders to knees.',
    setup: [
      'Place the camera at floor height, 2–3 m to your side.',
      'Kneel on a mat with hands under shoulders.',
      'Lean forward so shoulders, hips and knees form a line.',
    ],
    met: 2.8, // 02024 calisthenics, light
    angles: [
      { id: 'elbow', label: 'Elbow', kind: 'joint', joint: 'elbow' },
      { id: 'hip', label: 'Hip', kind: 'joint', joint: 'hip' },
    ],
    checks: [
      { angle: 'elbow', when: 'bottom', good: [50, 95], ok: [45, 115], cue: 'Lower your chest closer to the floor', why: 'Reaching ~90° elbow flexion trains the full pressing range.', weight: 2 },
      { angle: 'hip', when: 'active', good: [160, 180], ok: [145, 180], cue: 'Push hips forward, stay in line', why: 'Piking at the hips turns the press into a partial rep and reduces chest loading.', weight: 2 },
    ],
    reps: { driver: 'elbow', start: 'high', enter: 150, exit: 165, target: 95 },
  },
  {
    id: 'diamond-push-up',
    name: 'Diamond Push-up',
    category: 'calisthenics',
    icon: '💎',
    mode: 'reps',
    camera: 'side',
    difficulty: 2,
    equipment: [],
    muscles: ['triceps', 'chest', 'front delts', 'core'],
    summary: 'Close-hand push-up with thumbs and index fingers forming a diamond to emphasise the triceps.',
    setup: [
      'Place the camera at floor height, 2–3 m to your side.',
      'Hands together under your chest in a diamond shape.',
      'Legs straight, body in one line, whole body in frame.',
    ],
    met: 3.8,
    angles: [
      { id: 'elbow', label: 'Elbow', kind: 'joint', joint: 'elbow' },
      { id: 'bodyLine', label: 'Body line', kind: 'joint', joint: 'bodyLine' },
      { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee' },
    ],
    checks: [
      { angle: 'elbow', when: 'bottom', good: [50, 100], ok: [45, 120], cue: 'Lower until chest nears your hands', why: 'A narrow hand base raises triceps and pectoralis EMG over a wide base (Cogley 2005 JSCR, doi:10.1519/15094.1); it only counts through full depth.', weight: 2 },
      { angle: 'bodyLine', when: 'active', good: [165, 180], ok: [155, 180], cue: 'Brace your core, keep hips in line', why: 'A sagging or piked trunk reduces load on the pressing muscles and stresses the low back.', weight: 2 },
      { angle: 'knee', when: 'any', good: [160, 180], ok: [150, 180], cue: 'Keep your legs straight', why: 'Straight legs keep the full body lever and tension.' },
    ],
    reps: { driver: 'elbow', start: 'high', enter: 150, exit: 165, target: 100 },
  },
  {
    id: 'pike-push-up',
    name: 'Pike Push-up',
    category: 'calisthenics',
    icon: '🔺',
    mode: 'reps',
    camera: 'side',
    difficulty: 2,
    equipment: [],
    muscles: ['shoulders', 'triceps', 'upper chest'],
    summary: 'Inverted-V push-up that lowers the head toward the floor to build overhead pressing strength.',
    setup: [
      'Place the camera at floor height, 2–3 m to your side.',
      'Start in a push-up, then walk feet in and lift hips high.',
      'Keep arms and legs as straight as you can.',
    ],
    met: 3.8,
    angles: [
      { id: 'elbow', label: 'Elbow', kind: 'joint', joint: 'elbow' },
      { id: 'hip', label: 'Hip', kind: 'joint', joint: 'hip' },
      { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee' },
    ],
    checks: [
      { angle: 'elbow', when: 'bottom', good: [55, 100], ok: [45, 120], cue: 'Lower your head closer to the floor', why: 'Deeper elbow flexion takes the deltoids through a fuller overhead-press range.', weight: 2 },
      { angle: 'hip', when: 'active', good: [50, 100], ok: [40, 120], cue: 'Keep your hips high', why: 'A tight pike keeps the torso near vertical so the shoulders, not the chest, do the pressing.', weight: 2 },
      { angle: 'knee', when: 'any', good: [155, 180], ok: [140, 180], cue: 'Straighten your legs', why: 'Straight legs hold the pike angle; mild bend is acceptable with tight hamstrings.' },
    ],
    reps: { driver: 'elbow', start: 'high', enter: 150, exit: 165, target: 100 },
  },
  {
    id: 'pull-up',
    name: 'Pull-up',
    category: 'calisthenics',
    icon: '🧗',
    mode: 'reps',
    camera: 'front',
    difficulty: 3,
    equipment: ['pull-up bar'],
    muscles: ['lats', 'biceps', 'rear delts', 'rhomboids'],
    summary: 'Overhand vertical pull from a dead hang until the chin clears the bar.',
    setup: [
      'Place the camera 3 m in front, framing bar to feet.',
      'Grip the bar overhand, slightly wider than shoulders.',
      'Start from a full dead hang.',
    ],
    met: 7.5, // 02020 calisthenics incl. pull-ups, vigorous
    angles: [
      { id: 'elbow', label: 'Elbow', kind: 'joint', joint: 'elbow', side: 'both' },
      { id: 'shoulders', label: 'Shoulder tilt', kind: 'segment', segment: 'shoulders', ref: 'horizontal' },
      { id: 'hips', label: 'Hip tilt', kind: 'segment', segment: 'hips', ref: 'horizontal' },
    ],
    checks: [
      { angle: 'elbow', when: 'bottom', good: [20, 90], ok: [20, 105], cue: 'Pull your chin over the bar', why: 'Dead hang to chin-over-bar spans ~93° of elbow motion in the pull-up (Youdas 2010 JSCR, doi:10.1519/JSC.0b013e3181f1598c), i.e. top ≈ 90° included.', weight: 2 },
      { angle: 'shoulders', when: 'active', good: [0, 6], ok: [0, 12], cue: 'Pull evenly with both arms', why: 'Shoulder tilt indicates one side is doing more of the work.' },
      { angle: 'hips', when: 'active', good: [0, 6], ok: [0, 12], cue: 'Keep hips square, no twisting', why: 'Hip rotation or swinging is a compensation for insufficient pulling strength.' },
    ],
    reps: { driver: 'elbow', start: 'high', enter: 140, exit: 155, target: 90, minRepMs: 1000 },
  },
  {
    id: 'chin-up',
    name: 'Chin-up',
    category: 'calisthenics',
    icon: '🙃',
    mode: 'reps',
    camera: 'side',
    difficulty: 3,
    equipment: ['pull-up bar'],
    muscles: ['lats', 'biceps', 'rhomboids'],
    summary: 'Underhand shoulder-width vertical pull from a dead hang until the chin clears the bar.',
    setup: [
      'Place the camera 3 m to your side, framing bar to feet.',
      'Grip the bar underhand at shoulder width.',
      'Start from a full dead hang.',
    ],
    met: 7.5, // 02020
    angles: [
      { id: 'elbow', label: 'Elbow', kind: 'joint', joint: 'elbow' },
      { id: 'hip', label: 'Hip', kind: 'joint', joint: 'hip' },
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical' },
    ],
    checks: [
      { angle: 'elbow', when: 'bottom', good: [20, 85], ok: [20, 100], cue: 'Pull your chin over the bar', why: 'Dead hang to chin-over-bar spans ~101° of elbow motion in the chin-up (Youdas 2010 JSCR, doi:10.1519/JSC.0b013e3181f1598c), i.e. top ≈ 80° included.', weight: 2 },
      { angle: 'hip', when: 'active', good: [150, 180], ok: [130, 180], cue: 'No kipping, keep legs still', why: 'Hip flexion swings generate momentum that reduces work done by the pulling muscles.' },
      { angle: 'trunk', when: 'active', good: [0, 20], ok: [0, 35], cue: 'Stay tall, avoid leaning back', why: 'Excessive lean turns the pull into a row and hides a short range of motion.' },
    ],
    reps: { driver: 'elbow', start: 'high', enter: 140, exit: 155, target: 85, minRepMs: 1000 },
  },
  {
    id: 'parallel-bar-dip',
    name: 'Parallel-bar Dip',
    category: 'calisthenics',
    icon: '🤸',
    mode: 'reps',
    camera: 'side',
    difficulty: 3,
    equipment: ['parallel bars'],
    muscles: ['triceps', 'chest', 'front delts'],
    summary: 'Supported dip lowering between parallel bars until the upper arms are about parallel to the floor.',
    setup: [
      'Place the camera 3 m to your side at hip height.',
      'Support yourself on locked arms between the bars.',
      'Keep your whole body in frame.',
    ],
    met: 7.5, // 02020
    angles: [
      { id: 'elbow', label: 'Elbow', kind: 'joint', joint: 'elbow' },
      { id: 'upperArm', label: 'Upper arm', kind: 'segment', segment: 'upperArm', ref: 'vertical' },
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical' },
    ],
    checks: [
      { angle: 'elbow', when: 'bottom', good: [70, 95], ok: [60, 110], cue: 'Lower until elbows reach 90°', why: 'About 90° elbow flexion gives full triceps and chest range without excessive shoulder extension.', weight: 2 },
      { angle: 'upperArm', when: 'bottom', good: [80, 180], ok: [70, 180], cue: 'Stop when upper arms are level', why: 'Letting the shoulders sink below the elbows overloads the anterior shoulder capsule.' },
      { angle: 'trunk', when: 'active', good: [0, 35], ok: [0, 50], cue: 'Keep your torso controlled, not folded', why: 'A moderate lean is normal, but excessive forward fold increases shoulder stress.' },
    ],
    reps: { driver: 'elbow', start: 'high', enter: 145, exit: 160, target: 95, minRepMs: 800 },
  },
  {
    id: 'bench-dip',
    name: 'Bench Dip',
    category: 'calisthenics',
    icon: '🪑',
    mode: 'reps',
    camera: 'side',
    difficulty: 1,
    equipment: ['bench'],
    muscles: ['triceps', 'front delts', 'chest'],
    summary: 'Triceps dip with hands on a bench behind you, lowering until the elbows reach about 90 degrees.',
    setup: [
      'Place the camera 2–3 m to your side at bench height.',
      'Hands on the bench edge behind you, fingers forward.',
      'Legs extended, hips close to the bench.',
    ],
    met: 3.8,
    angles: [
      { id: 'elbow', label: 'Elbow', kind: 'joint', joint: 'elbow' },
      { id: 'upperArm', label: 'Upper arm', kind: 'segment', segment: 'upperArm', ref: 'vertical' },
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical' },
    ],
    checks: [
      { angle: 'elbow', when: 'bottom', good: [75, 100], ok: [65, 115], cue: 'Lower until elbows reach 90°', why: 'About 90° elbow flexion works the triceps fully without extreme shoulder extension.', weight: 2 },
      { angle: 'upperArm', when: 'bottom', good: [80, 125], ok: [70, 140], cue: "Don't sink below arm level", why: 'Excessive depth forces the shoulder into end-range extension, a common source of anterior shoulder pain.' },
      { angle: 'trunk', when: 'active', good: [0, 20], ok: [0, 35], cue: 'Keep your back close to the bench', why: 'Staying upright and close keeps load on the triceps and off the shoulders.' },
    ],
    reps: { driver: 'elbow', start: 'high', enter: 145, exit: 160, target: 100 },
  },
  {
    id: 'bodyweight-squat',
    name: 'Bodyweight Squat',
    category: 'calisthenics',
    icon: '🦵',
    mode: 'reps',
    camera: 'side',
    difficulty: 1,
    equipment: [],
    muscles: ['quads', 'glutes', 'adductors'],
    summary: 'Air squat lowering the hips until the thighs are at least parallel to the floor.',
    setup: [
      'Place the camera 2–3 m to your side at hip height.',
      'Feet about shoulder width, toes slightly out.',
      'Keep your whole body in frame.',
    ],
    met: 3.8,
    angles: [
      { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee' },
      { id: 'hip', label: 'Hip', kind: 'joint', joint: 'hip' },
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical' },
      { id: 'ankle', label: 'Ankle', kind: 'joint', joint: 'ankle' },
    ],
    checks: [
      { angle: 'knee', when: 'bottom', good: [20, 80], ok: [20, 95], cue: 'Sit deeper, thighs to parallel', why: 'Parallel depth maximises quadriceps and gluteal activation compared with partial squats.', weight: 2 },
      { angle: 'trunk', when: 'bottom', good: [10, 50], ok: [0, 60], cue: 'Keep your chest up', why: 'Excessive forward lean shifts load to the lower back and hips.' },
      { angle: 'ankle', when: 'bottom', good: [40, 85], ok: [35, 95], cue: 'Keep your heels on the floor', why: 'Heel rise signals limited ankle dorsiflexion and moves stress onto the knees.' },
      { angle: 'hip', when: 'top', good: [165, 180], ok: [155, 180], cue: 'Squeeze glutes, hips fully through', why: 'Full hip extension at the top completes the gluteal range.' },
    ],
    reps: { driver: 'knee', start: 'high', enter: 150, exit: 165, target: 80 },
  },
  {
    id: 'jump-squat',
    name: 'Jump Squat',
    category: 'calisthenics',
    icon: '🐸',
    mode: 'reps',
    camera: 'side',
    difficulty: 2,
    equipment: [],
    muscles: ['quads', 'glutes', 'calves'],
    summary: 'Explosive squat that drives into a vertical jump and lands softly into the next rep.',
    setup: [
      'Place the camera 3 m to your side, leaving headroom for the jump.',
      'Feet shoulder width, arms free to swing.',
      'Clear the space around you.',
    ],
    met: 7.5, // 02020
    angles: [
      { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee' },
      { id: 'hip', label: 'Hip', kind: 'joint', joint: 'hip' },
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical' },
    ],
    checks: [
      { angle: 'knee', when: 'bottom', good: [70, 110], ok: [60, 130], cue: 'Load deeper before you jump', why: 'A countermovement to roughly parallel improves jump impulse and landing absorption.', weight: 2 },
      { angle: 'trunk', when: 'bottom', good: [10, 50], ok: [0, 60], cue: 'Keep your chest up', why: 'Excessive trunk flexion reduces vertical force and loads the lower back.' },
      { angle: 'knee', when: 'top', good: [165, 180], ok: [150, 180], cue: 'Extend fully through the jump', why: 'Complete triple extension at take-off is key for jump height.' },
      { angle: 'hip', when: 'top', good: [165, 180], ok: [150, 180], cue: 'Drive your hips all the way through', why: 'Full hip extension transfers gluteal power into the jump.' },
    ],
    reps: { driver: 'knee', start: 'high', enter: 145, exit: 160, target: 110, minRepMs: 800 },
  },
  {
    id: 'pistol-squat',
    name: 'Pistol Squat',
    category: 'calisthenics',
    icon: '🔫',
    mode: 'reps',
    camera: 'side',
    difficulty: 3,
    equipment: ['support (optional)'],
    muscles: ['quads', 'glutes', 'core', 'hip flexors'],
    summary: 'Single-leg squat to full depth with the free leg held forward; holding a support is fine.',
    setup: [
      'Place the camera 2–3 m to your side at hip height.',
      'Stand on the leg nearest the camera.',
      'Hold a doorframe or pole for assistance if needed.',
      'Turn around to train the other leg.',
    ],
    met: 3.8,
    angles: [
      { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee' },
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical' },
      { id: 'ankle', label: 'Ankle', kind: 'joint', joint: 'ankle' },
    ],
    checks: [
      { angle: 'knee', when: 'bottom', good: [20, 80], ok: [15, 105], cue: 'Sink deeper on the standing leg', why: 'Full-depth single-leg squats demand the most quadriceps and gluteal strength and balance.', weight: 2 },
      { angle: 'trunk', when: 'bottom', good: [15, 55], ok: [5, 70], cue: 'Reach forward, chest up', why: 'A moderate forward lean counterbalances the hips; folding over shifts load to the back.' },
      { angle: 'ankle', when: 'bottom', good: [30, 80], ok: [25, 92], cue: 'Keep your heel down', why: 'Heel rise shows limited dorsiflexion and destabilises the knee.' },
    ],
    reps: { driver: 'knee', start: 'high', enter: 145, exit: 160, target: 80, minRepMs: 1200 },
  },
  {
    id: 'burpee',
    name: 'Burpee',
    category: 'calisthenics',
    icon: '🔥',
    mode: 'reps',
    camera: 'side',
    difficulty: 2,
    equipment: [],
    muscles: ['full body', 'quads', 'chest', 'core'],
    summary: 'Squat down, kick back to a plank, return and stand or jump — a full-body conditioning rep.',
    setup: [
      'Place the camera 3 m to your side at hip height.',
      'Leave room to kick back into a plank.',
      'Make sure standing and plank both fit in frame.',
    ],
    met: 7.5, // 02020 lists burpees
    angles: [
      { id: 'trunk', label: 'Trunk', kind: 'segment', segment: 'trunk', ref: 'vertical' },
      { id: 'bodyLine', label: 'Body line', kind: 'joint', joint: 'bodyLine' },
      { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee' },
      { id: 'hip', label: 'Hip', kind: 'joint', joint: 'hip' },
    ],
    checks: [
      { angle: 'trunk', when: 'bottom', good: [70, 100], ok: [60, 110], cue: 'Kick all the way back to plank', why: 'Reaching a full plank is the standard for a complete burpee rep.', weight: 2 },
      { angle: 'bodyLine', when: 'bottom', good: [160, 180], ok: [145, 180], cue: "Keep hips level in the plank", why: 'Sagging hips in the plank phase stress the lumbar spine; a crouch without the kick-back fails this check.', weight: 3 },
      { angle: 'knee', when: 'top', good: [160, 180], ok: [145, 180], cue: 'Stand all the way up', why: 'Full extension at the top completes each rep.' },
      { angle: 'hip', when: 'top', good: [160, 180], ok: [145, 180], cue: 'Open your hips fully at the top', why: 'Full hip extension distinguishes a complete rep from a partial one.' },
    ],
    reps: { driver: 'trunk', start: 'low', enter: 45, exit: 30, target: 70, minRepMs: 1500 },
  },
  {
    id: 'mountain-climber',
    name: 'Mountain Climber',
    category: 'calisthenics',
    icon: '⛰️',
    mode: 'reps',
    camera: 'side',
    difficulty: 2,
    equipment: [],
    muscles: ['core', 'hip flexors', 'shoulders', 'quads'],
    summary: 'Alternate driving each knee toward the chest from a high plank while keeping the hips level.',
    setup: [
      'One rep = left + right leg; counted on the leg nearer the camera.',
      'Place the camera at floor height, 2–3 m to your side.',
      'Start in a high plank, hands under shoulders.',
      'Keep your whole body in frame.',
    ],
    met: 7.5, // 02020
    angles: [
      { id: 'hip', label: 'Hip', kind: 'joint', joint: 'hip' },
      { id: 'trunk', label: 'Trunk', kind: 'segment', segment: 'trunk', ref: 'vertical' },
      { id: 'elbow', label: 'Elbow', kind: 'joint', joint: 'elbow' },
    ],
    checks: [
      { angle: 'hip', when: 'bottom', good: [40, 95], ok: [30, 120], cue: 'Drive your knee to your chest', why: 'Full hip flexion is what loads the hip flexors and anterior core.', weight: 2 },
      { angle: 'trunk', when: 'active', good: [65, 95], ok: [55, 105], cue: 'Keep your hips level', why: 'Piking or sagging hips removes the anti-extension core demand of the plank.', weight: 2 },
      { angle: 'elbow', when: 'any', good: [155, 180], ok: [145, 180], cue: 'Keep your arms straight', why: 'Locked arms keep shoulders stacked over the hands for a stable base.' },
    ],
    reps: { driver: 'hip', start: 'high', enter: 140, exit: 155, target: 95, minRepMs: 350, alternating: true },
  },
  {
    id: 'crunch',
    name: 'Crunch',
    category: 'calisthenics',
    icon: '🥨',
    mode: 'reps',
    camera: 'side',
    difficulty: 1,
    equipment: ['mat'],
    muscles: ['rectus abdominis', 'obliques'],
    summary: 'Lying on your back with knees bent, curl the shoulder blades off the floor and lower with control.',
    setup: [
      'Place the camera at floor height, 2 m to your side.',
      'Lie on your back, knees bent, feet flat.',
      'Hands across chest or lightly behind ears.',
    ],
    met: 2.8, // 02024 lists crunches, plank
    angles: [
      { id: 'trunk', label: 'Trunk', kind: 'segment', segment: 'trunk', ref: 'vertical' },
      { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee' },
    ],
    checks: [
      { angle: 'trunk', when: 'bottom', good: [60, 77], ok: [50, 81], cue: 'Curl shoulder blades off the floor', why: 'Abdominal activation peaks in the first ~30° of trunk flexion; with the low back on the mat that lifts the hip-to-shoulder line only ~15–20°.', weight: 2 },
      { angle: 'trunk', when: 'top', good: [82, 100], ok: [75, 105], cue: 'Lower all the way down', why: 'Returning to the floor each rep ensures full range and consistent counting.' },
      { angle: 'knee', when: 'any', good: [70, 110], ok: [55, 130], cue: 'Keep knees bent, feet flat', why: 'Bent knees reduce hip-flexor contribution and lumbar strain.' },
    ],
    reps: { driver: 'trunk', start: 'high', enter: 81, exit: 86, target: 76, minRepMs: 700 },
  },
  {
    id: 'lying-leg-raise',
    name: 'Lying Leg Raise',
    category: 'calisthenics',
    icon: '🦿',
    mode: 'reps',
    camera: 'side',
    difficulty: 2,
    equipment: ['mat'],
    muscles: ['lower abs', 'hip flexors'],
    summary: 'Lying on your back, raise straight legs to vertical and lower them with control.',
    setup: [
      'Place the camera at floor height, 2–3 m to your side.',
      'Lie flat, legs straight, hands under hips or by your sides.',
      'Keep your whole body in frame.',
    ],
    met: 3.8,
    angles: [
      { id: 'hip', label: 'Hip', kind: 'joint', joint: 'hip' },
      { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee' },
      { id: 'trunk', label: 'Trunk', kind: 'segment', segment: 'trunk', ref: 'vertical' },
    ],
    checks: [
      { angle: 'hip', when: 'bottom', good: [60, 95], ok: [55, 115], cue: 'Raise legs up to vertical', why: 'Lifting to ~90° hip flexion works the full range of the hip flexors and lower abdominals.', weight: 2 },
      { angle: 'knee', when: 'any', good: [160, 180], ok: [145, 180], cue: 'Keep your legs straight', why: 'Bending the knees shortens the lever and reduces the load.' },
      { angle: 'trunk', when: 'any', good: [80, 100], ok: [70, 110], cue: 'Keep shoulders down on the mat', why: 'Lifting the torso means momentum or a sit-up is replacing the leg raise.' },
    ],
    reps: { driver: 'hip', start: 'high', enter: 150, exit: 165, target: 95, minRepMs: 1000 },
  },
  {
    id: 'plank',
    name: 'Plank',
    category: 'calisthenics',
    icon: '🧱',
    mode: 'hold',
    camera: 'side',
    difficulty: 1,
    equipment: ['mat'],
    muscles: ['core', 'shoulders', 'glutes'],
    summary: 'Forearm plank holding a straight line from shoulders through hips to ankles.',
    setup: [
      'Place the camera at floor height, 2–3 m to your side.',
      'Forearms on the floor, elbows under shoulders.',
      'Legs straight, body in one line.',
    ],
    met: 2.8, // 02024
    angles: [
      { id: 'bodyLine', label: 'Body line', kind: 'joint', joint: 'bodyLine' },
      { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee' },
      { id: 'elbow', label: 'Elbow', kind: 'joint', joint: 'elbow' },
      { id: 'upperArm', label: 'Upper arm', kind: 'segment', segment: 'upperArm', ref: 'vertical' },
    ],
    checks: [
      { angle: 'bodyLine', when: 'hold', good: [165, 180], ok: [155, 180], cue: 'Keep hips level with shoulders', why: 'A neutral line maximises anti-extension core loading and spares the low back.', weight: 3 },
      { angle: 'knee', when: 'hold', good: [165, 180], ok: [155, 180], cue: 'Straighten your legs', why: 'Straight legs keep the full-body lever the plank depends on.' },
      { angle: 'elbow', when: 'hold', good: [75, 105], ok: [65, 120], cue: 'Forearms flat, elbows at 90°', why: 'A right-angle elbow keeps load evenly shared by the shoulders.' },
      { angle: 'upperArm', when: 'hold', good: [165, 180], ok: [150, 180], cue: 'Stack elbows under shoulders', why: 'Vertical upper arms support the body without straining the shoulder.' },
    ],
    hold: { targetSec: 60 },
  },
  {
    id: 'side-plank',
    name: 'Side Plank',
    category: 'calisthenics',
    icon: '📐',
    mode: 'hold',
    camera: 'front',
    difficulty: 2,
    equipment: ['mat'],
    muscles: ['obliques', 'quadratus lumborum', 'glute medius', 'shoulders'],
    summary: 'Support on one forearm and the side of the feet with the body in a straight line.',
    setup: [
      'Place the camera at floor height, 2–3 m in front of you.',
      'Lie on your side, elbow under shoulder, feet stacked.',
      'Lift hips so the body faces the camera in one line.',
    ],
    met: 2.8, // 02024
    angles: [
      { id: 'bodyLine', label: 'Body line', kind: 'joint', joint: 'bodyLine', side: 'both' },
      { id: 'hip', label: 'Hip', kind: 'joint', joint: 'hip', side: 'both' },
      { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee', side: 'both' },
    ],
    checks: [
      { angle: 'bodyLine', when: 'hold', good: [165, 180], ok: [155, 180], cue: 'Lift your hips higher', why: 'A straight lateral line maximises oblique and quadratus lumborum activation.', weight: 3 },
      { angle: 'hip', when: 'hold', good: [165, 180], ok: [155, 180], cue: "Don't bend at the hips", why: 'Hip flexion lets the trunk fold and offloads the lateral core.' },
      { angle: 'knee', when: 'hold', good: [165, 180], ok: [155, 180], cue: 'Keep your legs straight', why: 'Straight legs keep the full lever length.' },
    ],
    hold: { targetSec: 30 },
  },
  {
    id: 'hollow-body-hold',
    name: 'Hollow Body Hold',
    category: 'calisthenics',
    icon: '🍌',
    mode: 'hold',
    camera: 'side',
    difficulty: 2,
    equipment: ['mat'],
    muscles: ['rectus abdominis', 'hip flexors', 'obliques'],
    summary: 'Lying on your back, lift shoulders and straight legs off the floor with arms overhead and the low back pressed down.',
    setup: [
      'Place the camera at floor height, 2–3 m to your side.',
      'Lie on your back, press your low back into the floor.',
      'Lift arms overhead, shoulders and legs off the floor.',
    ],
    met: 3.8,
    angles: [
      { id: 'hip', label: 'Hip', kind: 'joint', joint: 'hip' },
      { id: 'thigh', label: 'Leg height', kind: 'segment', segment: 'thigh', ref: 'vertical' },
      { id: 'trunk', label: 'Trunk', kind: 'segment', segment: 'trunk', ref: 'vertical' },
      { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee' },
      { id: 'shoulder', label: 'Arm position', kind: 'joint', joint: 'shoulder' },
    ],
    checks: [
      { angle: 'hip', when: 'hold', good: [105, 160], ok: [90, 172], cue: 'Hollow out, curl ribs down', why: 'The hollow position relies on posterior pelvic tilt and slight trunk flexion to load the abdominals.', weight: 2 },
      { angle: 'thigh', when: 'hold', good: [50, 75], ok: [40, 85], cue: 'Keep legs low but off floor', why: 'Legs 15–40° off the floor create a long lever; lower than that the back tends to arch.' },
      { angle: 'trunk', when: 'hold', good: [55, 82], ok: [45, 88], cue: 'Lift your shoulder blades off floor', why: 'Raised shoulders complete the hollow shape and engage the upper abdominals.' },
      { angle: 'knee', when: 'hold', good: [160, 180], ok: [145, 180], cue: 'Keep your legs straight', why: 'Straight legs maximise the lever and training effect.' },
      { angle: 'shoulder', when: 'hold', good: [150, 180], ok: [120, 180], cue: 'Reach your arms overhead', why: 'Overhead arms lengthen the lever and increase core demand.' },
    ],
    hold: { targetSec: 30 },
  },
  {
    id: 'wall-sit',
    name: 'Wall Sit',
    category: 'calisthenics',
    icon: '🧍',
    mode: 'hold',
    camera: 'side',
    difficulty: 1,
    equipment: ['wall'],
    muscles: ['quads', 'glutes'],
    summary: 'Isometric squat with the back against a wall and thighs parallel to the floor.',
    setup: [
      'Place the camera 2–3 m to your side at hip height.',
      'Back flat against a wall, slide down.',
      'Stop with knees and hips at 90°, ankles under knees.',
    ],
    met: 2.8,
    angles: [
      { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee' },
      { id: 'hip', label: 'Hip', kind: 'joint', joint: 'hip' },
      { id: 'trunk', label: 'Trunk', kind: 'segment', segment: 'trunk', ref: 'vertical' },
      { id: 'shin', label: 'Shin', kind: 'segment', segment: 'shin', ref: 'vertical' },
    ],
    checks: [
      { angle: 'knee', when: 'hold', good: [80, 100], ok: [70, 115], cue: 'Slide down until thighs are level', why: 'A 90° knee angle is the standard wall-sit position and maximises quadriceps demand.', weight: 3 },
      { angle: 'hip', when: 'hold', good: [80, 105], ok: [70, 120], cue: 'Sit back, hips at 90°', why: 'Hip angle near 90° confirms the thighs are parallel to the floor.' },
      { angle: 'trunk', when: 'hold', good: [0, 12], ok: [0, 22], cue: 'Keep your back on the wall', why: 'An upright trunk against the wall isolates the quadriceps.' },
      { angle: 'shin', when: 'hold', good: [0, 10], ok: [0, 20], cue: 'Ankles directly under knees', why: 'Vertical shins limit shear stress on the knee joint.' },
    ],
    hold: { targetSec: 60 },
  },
  {
    id: 'l-sit',
    name: 'L-sit',
    category: 'calisthenics',
    icon: '🪜',
    mode: 'hold',
    camera: 'side',
    difficulty: 3,
    equipment: ['parallettes or dip bars (optional)'],
    muscles: ['hip flexors', 'rectus abdominis', 'triceps', 'shoulders'],
    summary: 'Support on straight arms with legs held straight out in front, forming an L.',
    setup: [
      'Place the camera 2–3 m to your side at hip height.',
      'Hands on floor, parallettes or bars beside your hips.',
      'Press up on locked arms and lift straight legs forward.',
    ],
    met: 3.8,
    angles: [
      { id: 'hip', label: 'Hip', kind: 'joint', joint: 'hip' },
      { id: 'thigh', label: 'Leg height', kind: 'segment', segment: 'thigh', ref: 'vertical' },
      { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee' },
      { id: 'elbow', label: 'Elbow', kind: 'joint', joint: 'elbow' },
      { id: 'trunk', label: 'Trunk', kind: 'segment', segment: 'trunk', ref: 'vertical' },
    ],
    checks: [
      { angle: 'thigh', when: 'hold', good: [70, 95], ok: [60, 110], cue: 'Lift legs to hip height', why: 'Horizontal legs define the L-sit and demand maximal hip-flexor and abdominal strength.', weight: 2 },
      { angle: 'hip', when: 'hold', good: [75, 100], ok: [65, 115], cue: 'Fold at the hips to 90°', why: 'A 90° hip angle with upright trunk is the standard L shape.' },
      { angle: 'knee', when: 'hold', good: [160, 180], ok: [145, 180], cue: 'Lock your knees straight', why: 'Straight legs are the full L-sit; tucking reduces the load.' },
      { angle: 'elbow', when: 'hold', good: [165, 180], ok: [155, 180], cue: 'Lock your arms, push shoulders down', why: 'Locked elbows and depressed shoulders provide a stable support base.' },
      { angle: 'trunk', when: 'hold', good: [0, 20], ok: [0, 30], cue: 'Sit tall, chest up', why: 'An upright trunk keeps the hip-flexion demand on the legs.' },
    ],
    hold: { targetSec: 15 },
  },
];
