import type { AngleDef, Check, ExerciseDef } from '../types.js';

// MET: 2024 Adult Compendium (Herrmann 2024 J Sport Health Sci, doi:10.1016/j.jshs.2023.10.010; codes at pacompendium.com).

// Shared angle definitions (ids are local to each exercise).
const KNEE: AngleDef = { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee' };
const KNEE_B: AngleDef = { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee', side: 'both' };
const HIP: AngleDef = { id: 'hip', label: 'Hip', kind: 'joint', joint: 'hip' };
const ELBOW: AngleDef = { id: 'elbow', label: 'Elbow', kind: 'joint', joint: 'elbow' };
const ELBOW_B: AngleDef = { id: 'elbow', label: 'Elbow', kind: 'joint', joint: 'elbow', side: 'both' };
const SHOULDER: AngleDef = { id: 'shoulder', label: 'Shoulder', kind: 'joint', joint: 'shoulder' };
const SHOULDER_B: AngleDef = { id: 'shoulder', label: 'Shoulder', kind: 'joint', joint: 'shoulder', side: 'both' };
const ANKLE: AngleDef = { id: 'ankle', label: 'Ankle', kind: 'joint', joint: 'ankle' };
const TRUNK: AngleDef = { id: 'trunk', label: 'Torso lean', kind: 'segment', segment: 'trunk', ref: 'vertical' };
const SHIN: AngleDef = { id: 'shin', label: 'Shin angle', kind: 'segment', segment: 'shin', ref: 'vertical' };
const UPPER_ARM: AngleDef = { id: 'upperArm', label: 'Upper arm', kind: 'segment', segment: 'upperArm', ref: 'vertical' };
const FOREARM: AngleDef = { id: 'forearm', label: 'Forearm', kind: 'segment', segment: 'forearm', ref: 'vertical' };
const FOREARM_B: AngleDef = { id: 'forearm', label: 'Forearm', kind: 'segment', segment: 'forearm', ref: 'vertical', side: 'both' };
const SHOULDERS_TILT: AngleDef = { id: 'shoulders', label: 'Shoulder level', kind: 'segment', segment: 'shoulders', ref: 'horizontal' };
const HIPS_TILT: AngleDef = { id: 'hips', label: 'Hip level', kind: 'segment', segment: 'hips', ref: 'horizontal' };
const FEET: AngleDef = { id: 'feet', label: 'Stance width', kind: 'spread', what: 'feet' };
const KNEES: AngleDef = { id: 'knees', label: 'Knee width', kind: 'spread', what: 'knees' };
const HANDS: AngleDef = { id: 'hands', label: 'Grip width', kind: 'spread', what: 'hands' };

// Shared checks.
const kneeLockout: Check = {
  angle: 'knee', when: 'top', good: [165, 180], ok: [155, 180],
  cue: 'Stand fully, knees straight', why: 'Full knee extension completes the rep and resets position.',
};
const hipLockout: Check = {
  angle: 'hip', when: 'top', good: [165, 180], ok: [155, 180],
  cue: 'Finish tall, squeeze glutes', why: 'Full hip extension at lockout trains the glutes through complete range.',
};
const levelShoulders: Check = {
  angle: 'shoulders', when: 'any', good: [0, 5], ok: [0, 10],
  cue: 'Keep shoulders level', why: 'Shoulder tilt signals side-to-side imbalance or compensation.',
};

export const GYM: ExerciseDef[] = [
  {
    id: 'back-squat',
    name: 'Back Squat',
    category: 'gym',
    icon: '🏋️',
    mode: 'reps',
    camera: 'side',
    difficulty: 2,
    equipment: ['barbell', 'squat rack'],
    muscles: ['quadriceps', 'glutes', 'adductors', 'erector spinae'],
    summary: 'Barbell on the upper back, squat to parallel or below and stand up.',
    setup: [
      'Place camera side-on at hip height, 2–3 m away.',
      'Bar on upper traps, feet shoulder-width, toes slightly out.',
      'Brace your core before each rep.',
    ],
    met: 5.0, // 02052 squats/deadlift
    angles: [KNEE, HIP, TRUNK, SHIN],
    reps: { driver: 'knee', start: 'high', enter: 150, exit: 165, target: 80, minRepMs: 1000 },
    checks: [
      { angle: 'knee', when: 'bottom', good: [0, 80], ok: [0, 95], cue: 'Sit deeper, reach parallel', why: 'Parallel is ≥100° knee flexion (included ≤80°); below-parallel 3RM squats reach ~120–126° (Larsen 2021 Front Sports Act Living, doi:10.3389/fspor.2021.719013). Knee-extensor effort rises with depth (Bryanton 2012 JSCR, doi:10.1519/JSC.0b013e31826791a7).' },
      { angle: 'trunk', when: 'bottom', good: [15, 55], ok: [5, 65], cue: 'Keep chest up', why: 'Torso lean at depth is ~47° high-bar to ~57° low-bar (Larsen 2021, doi:10.3389/fspor.2021.719013); more shifts load to the lower back.' },
      { angle: 'shin', when: 'bottom', good: [5, 40], ok: [0, 50], cue: 'Sit back, control knee travel', why: 'Some forward knee travel is normal: blocking it raised hip torque ~10× and trunk lean, while free travel raised knee torque ~28% (Fry 2003 JSCR, doi:10.1519/1533-4287(2003)017<0629:EOKPOH>2.0.CO;2).' },
      hipLockout,
    ],
  },
  {
    id: 'front-squat',
    name: 'Front Squat',
    category: 'gym',
    icon: '🏋️',
    mode: 'reps',
    camera: 'side',
    difficulty: 3,
    equipment: ['barbell', 'squat rack'],
    muscles: ['quadriceps', 'glutes', 'upper back', 'core'],
    summary: 'Bar racked on the front delts, squat with an upright torso.',
    setup: [
      'Place camera side-on at hip height, 2–3 m away.',
      'Rack bar on front delts, elbows high.',
      'Feet shoulder-width, toes slightly out.',
    ],
    met: 5.0, // 02052
    angles: [KNEE, HIP, TRUNK, SHIN, UPPER_ARM],
    reps: { driver: 'knee', start: 'high', enter: 150, exit: 165, target: 80, minRepMs: 1000 },
    checks: [
      { angle: 'knee', when: 'bottom', good: [0, 80], ok: [0, 95], cue: 'Sit deeper, reach parallel', why: 'Full depth maximises quadriceps work; the front squat matches back-squat muscle recruitment with lower knee compression (Gullett 2009 JSCR, doi:10.1519/JSC.0b013e31818546bb).' },
      { angle: 'trunk', when: 'bottom', good: [0, 30], ok: [0, 40], cue: 'Stay upright, chest tall', why: 'A forward-tipping torso lets the bar roll off the rack position.' },
      { angle: 'shin', when: 'bottom', good: [15, 45], ok: [5, 55], cue: 'Let knees travel forward over toes', why: 'Forward knee travel allows an upright torso in the front squat.' },
      { angle: 'upperArm', when: 'active', good: [60, 110], ok: [45, 130], cue: 'Drive elbows up', why: 'Dropping elbows collapses the front rack and upper back.' },
    ],
  },
  {
    id: 'goblet-squat',
    name: 'Goblet Squat',
    category: 'gym',
    icon: '🏋️',
    mode: 'reps',
    camera: 'side',
    difficulty: 1,
    equipment: ['dumbbell or kettlebell'],
    muscles: ['quadriceps', 'glutes', 'core'],
    summary: 'Hold a weight at the chest and squat deep with an upright torso.',
    setup: [
      'Place camera side-on at hip height, 2–3 m away.',
      'Hold dumbbell vertically against your chest.',
      'Feet shoulder-width, toes slightly out.',
    ],
    met: 5.0, // 02052
    angles: [KNEE, HIP, TRUNK, SHIN],
    reps: { driver: 'knee', start: 'high', enter: 150, exit: 165, target: 80, minRepMs: 800 },
    checks: [
      { angle: 'knee', when: 'bottom', good: [0, 80], ok: [0, 95], cue: 'Sit deeper, elbows inside knees', why: 'Full depth trains quadriceps and hip mobility through full range.' },
      { angle: 'trunk', when: 'bottom', good: [0, 35], ok: [0, 45], cue: 'Keep chest up behind the weight', why: 'The front load rewards an upright torso and spares the lower back.' },
      { angle: 'shin', when: 'bottom', good: [10, 45], ok: [5, 55], cue: 'Keep heels down', why: 'Excess shin angle usually means heels lifting and weight on toes.' },
    ],
  },
  {
    id: 'sumo-squat',
    name: 'Sumo Squat',
    category: 'gym',
    icon: '🏋️',
    mode: 'reps',
    camera: 'front',
    difficulty: 1,
    equipment: ['dumbbell or kettlebell'],
    muscles: ['adductors', 'glutes', 'quadriceps'],
    summary: 'Wide-stance squat with toes out, holding a weight between the legs.',
    setup: [
      'Place camera facing you at hip height, 2–3 m away.',
      'Stand wide, about 1.5–2× shoulder width, toes out.',
      'Hold the weight with straight arms between legs.',
    ],
    met: 5.0, // 02052
    angles: [KNEE_B, FEET, KNEES, SHOULDERS_TILT, HIPS_TILT],
    reps: { driver: 'knee', start: 'high', enter: 150, exit: 165, target: 110, minRepMs: 800 },
    checks: [
      { angle: 'knee', when: 'bottom', good: [70, 110], ok: [60, 125], cue: 'Sink hips lower', why: 'Deeper sumo squats increase adductor and glute activation.' },
      { angle: 'feet', when: 'any', good: [1.4, 2.2], ok: [1.2, 2.6], cue: 'Widen your stance', why: 'A wide stance defines the sumo pattern and targets the adductors.' },
      { angle: 'knees', when: 'bottom', good: [1.4, 2.4], ok: [1.0, 2.8], cue: 'Push knees out over toes', why: 'Knee valgus under load increases stress on the knee ligaments.' },
      { angle: 'hips', when: 'bottom', good: [0, 5], ok: [0, 10], cue: 'Keep hips level', why: 'Hip shift at depth signals a strength or mobility asymmetry.' },
      levelShoulders,
    ],
  },
  {
    id: 'bench-press',
    name: 'Bench Press',
    category: 'gym',
    icon: '🏋️',
    mode: 'reps',
    camera: 'side',
    difficulty: 2,
    equipment: ['barbell', 'flat bench', 'rack'],
    muscles: ['pectorals', 'anterior deltoids', 'triceps'],
    summary: 'Lie on a flat bench, lower the bar to the chest and press to lockout.',
    setup: [
      'Place camera side-on at bench height, 2–3 m away.',
      'Eyes under the bar, feet flat, shoulder blades pinched.',
      'Grip slightly wider than shoulders.',
    ],
    met: 3.5, // 02054 resistance training, 8-15 reps
    angles: [ELBOW, SHOULDER, FOREARM],
    reps: { driver: 'elbow', start: 'high', enter: 145, exit: 160, target: 95, minRepMs: 1000 },
    checks: [
      { angle: 'elbow', when: 'bottom', good: [0, 95], ok: [0, 110], cue: 'Lower the bar to your chest', why: 'Full-range bench press builds more strength than partial ROM (Martínez-Cava 2022 JSCR, doi:10.1519/JSC.0000000000003391); side-on, elbow tuck shrinks the projected angle, so no lower bound.' },
      { angle: 'forearm', when: 'active', good: [0, 15], ok: [0, 25], cue: 'Stack wrists over elbows', why: 'Vertical forearms transfer force efficiently and protect the wrists.' },
    ],
  },
  {
    id: 'incline-bench-press',
    name: 'Incline Bench Press',
    category: 'gym',
    icon: '🏋️',
    mode: 'reps',
    camera: 'side',
    difficulty: 2,
    equipment: ['barbell', 'incline bench'],
    muscles: ['upper pectorals', 'anterior deltoids', 'triceps'],
    summary: 'Press a barbell from the upper chest on a 30–45° incline bench.',
    setup: [
      'Place camera side-on at bench height, 2–3 m away.',
      'Set bench to 30–45°, feet flat, blades pinched.',
      'Grip slightly wider than shoulders.',
    ],
    met: 3.5, // 02054
    angles: [ELBOW, SHOULDER, FOREARM],
    reps: { driver: 'elbow', start: 'high', enter: 145, exit: 160, target: 95, minRepMs: 1000 },
    checks: [
      { angle: 'elbow', when: 'bottom', good: [0, 95], ok: [0, 110], cue: 'Lower bar to upper chest', why: 'Full range emphasises the clavicular pectoral head; side-on, elbow tuck shrinks the projected angle, so no lower bound.' },
      { angle: 'forearm', when: 'active', good: [0, 15], ok: [0, 25], cue: 'Stack wrists over elbows', why: 'Vertical forearms keep the bar path efficient.' },
    ],
  },
  {
    id: 'overhead-press',
    name: 'Overhead Press',
    category: 'gym',
    icon: '🏋️',
    mode: 'reps',
    camera: 'side',
    difficulty: 2,
    equipment: ['barbell'],
    muscles: ['deltoids', 'triceps', 'upper trapezius', 'core'],
    summary: 'Standing strict press of a barbell from the shoulders to overhead lockout.',
    setup: [
      'Place camera side-on at chest height, 2–3 m away.',
      'Bar on front delts, grip just outside shoulders.',
      'Squeeze glutes and brace before pressing.',
    ],
    met: 3.5, // 02054
    angles: [SHOULDER, ELBOW, TRUNK, KNEE],
    reps: { driver: 'shoulder', start: 'low', enter: 100, exit: 80, target: 160, minRepMs: 1000 },
    checks: [
      { angle: 'shoulder', when: 'bottom', good: [160, 180], ok: [145, 180], cue: 'Press the bar fully overhead', why: 'Full shoulder flexion finishes the lift with the bar over mid-foot.' },
      { angle: 'elbow', when: 'bottom', good: [165, 180], ok: [150, 180], cue: 'Lock out elbows overhead', why: 'A locked-out elbow stabilises the load on the skeleton.' },
      { angle: 'trunk', when: 'any', good: [0, 10], ok: [0, 20], cue: "Brace, don't lean back", why: 'Excess lumbar lean-back increases spinal extension load.' },
      { angle: 'knee', when: 'active', good: [165, 180], ok: [155, 180], cue: 'Keep legs straight, strict press', why: 'Knee dip turns a strict press into a push press.' },
    ],
  },
  {
    id: 'conventional-deadlift',
    name: 'Conventional Deadlift',
    category: 'gym',
    icon: '🏋️',
    mode: 'reps',
    camera: 'side',
    difficulty: 3,
    equipment: ['barbell', 'plates'],
    muscles: ['glutes', 'hamstrings', 'erector spinae', 'quadriceps', 'lats'],
    summary: 'Lift a barbell from the floor to standing lockout with a neutral spine.',
    setup: [
      'Place camera side-on at hip height, 2–3 m away.',
      'Bar over mid-foot, feet hip-width, hands outside knees.',
      'Brace, flatten back, pull slack out of the bar.',
    ],
    met: 5.0, // 02052 deadlift
    angles: [HIP, KNEE, TRUNK],
    reps: { driver: 'hip', start: 'high', enter: 140, exit: 160, target: 100, minRepMs: 1200 },
    checks: [
      { angle: 'hip', when: 'bottom', good: [55, 100], ok: [45, 115], cue: 'Hinge down to reach the bar', why: 'Returning the bar to the floor completes the full deadlift range.' },
      { angle: 'knee', when: 'bottom', good: [100, 145], ok: [85, 160], cue: 'Set shins to the bar', why: 'Conventional start uses moderate knee bend, neither squat nor stiff-leg.' },
      { angle: 'trunk', when: 'bottom', good: [35, 65], ok: [25, 75], cue: 'Shoulders slightly ahead of the bar', why: 'Torso angle in this band balances hip and knee moment arms.' },
      hipLockout,
      { angle: 'trunk', when: 'top', good: [0, 10], ok: [0, 20], cue: "Don't lean back at lockout", why: 'Hyperextending at lockout compresses the lumbar spine.' },
    ],
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    category: 'gym',
    icon: '🏋️',
    mode: 'reps',
    camera: 'side',
    difficulty: 2,
    equipment: ['barbell or dumbbells'],
    muscles: ['hamstrings', 'glutes', 'erector spinae'],
    summary: 'Hip hinge with soft knees, lowering the bar along the legs to mid-shin.',
    setup: [
      'Place camera side-on at hip height, 2–3 m away.',
      'Stand tall holding bar at hips, feet hip-width.',
      'Unlock knees slightly and keep them fixed.',
    ],
    met: 5.0, // 02052
    angles: [HIP, KNEE, TRUNK, SHIN],
    reps: { driver: 'hip', start: 'high', enter: 150, exit: 165, target: 110, minRepMs: 1000 },
    checks: [
      { angle: 'hip', when: 'bottom', good: [70, 110], ok: [60, 125], cue: 'Push hips back further', why: 'A deep hinge loads the hamstrings at long muscle length.' },
      { angle: 'knee', when: 'active', good: [145, 175], ok: [130, 180], cue: 'Keep a soft, fixed knee', why: 'Bending the knees more turns the RDL into a squat.' },
      { angle: 'trunk', when: 'bottom', good: [50, 90], ok: [40, 100], cue: 'Hinge torso toward parallel, back flat', why: 'Torso angle reflects hinge depth while the spine stays neutral.' },
      { angle: 'shin', when: 'bottom', good: [0, 12], ok: [0, 20], cue: 'Keep shins vertical, hips back', why: 'Forward knee travel shifts work from hamstrings to quads.' },
    ],
  },
  {
    id: 'bent-over-row',
    name: 'Bent-Over Barbell Row',
    category: 'gym',
    icon: '🏋️',
    mode: 'reps',
    camera: 'side',
    difficulty: 2,
    equipment: ['barbell'],
    muscles: ['lats', 'rhomboids', 'rear deltoids', 'biceps', 'erector spinae'],
    summary: 'Hinged at the hips, row the barbell to the lower ribs.',
    setup: [
      'Place camera side-on at hip height, 2–3 m away.',
      'Hinge until torso is 45° or lower, soft knees.',
      'Arms hang straight, grip just outside knees.',
    ],
    met: 3.5, // 02054
    angles: [ELBOW, TRUNK, KNEE],
    reps: { driver: 'elbow', start: 'high', enter: 145, exit: 160, target: 95, minRepMs: 900 },
    checks: [
      { angle: 'elbow', when: 'bottom', good: [50, 95], ok: [40, 110], cue: 'Pull the bar to lower ribs', why: 'Full elbow flexion ensures complete scapular retraction.' },
      { angle: 'trunk', when: 'active', good: [40, 80], ok: [30, 90], cue: 'Stay bent over, no torso heave', why: 'Standing up during the pull uses momentum and reduces back work.' },
      { angle: 'knee', when: 'active', good: [135, 170], ok: [120, 180], cue: 'Keep soft, steady knees', why: 'Stable knees keep the hinge position fixed through the set.' },
    ],
  },
  {
    id: 'dumbbell-curl',
    name: 'Dumbbell Curl',
    category: 'gym',
    icon: '💪',
    mode: 'reps',
    camera: 'side',
    difficulty: 1,
    equipment: ['dumbbells'],
    muscles: ['biceps brachii', 'brachialis'],
    summary: 'Curl dumbbells from straight arms to the shoulders with palms up.',
    setup: [
      'Place camera side-on at chest height, 2 m away.',
      'Stand tall, dumbbells at sides, palms forward.',
      'Keep elbows close to your torso.',
    ],
    met: 3.5, // 02054
    angles: [ELBOW, UPPER_ARM, TRUNK],
    reps: { driver: 'elbow', start: 'high', enter: 130, exit: 150, target: 55 },
    checks: [
      { angle: 'elbow', when: 'bottom', good: [25, 55], ok: [20, 75], cue: 'Curl all the way up', why: 'Full elbow flexion trains the biceps through its full range.' },
      { angle: 'upperArm', when: 'any', good: [155, 180], ok: [140, 180], cue: 'Pin elbows to your sides', why: 'Elbows drifting forward shift work to the anterior deltoid.' },
      { angle: 'trunk', when: 'any', good: [0, 8], ok: [0, 15], cue: "Don't swing your torso", why: 'Torso swing adds momentum and reduces biceps loading.' },
      { angle: 'elbow', when: 'top', good: [155, 180], ok: [145, 180], cue: 'Lower fully to straight arms', why: 'Full eccentric range builds strength at long muscle length.' },
    ],
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    category: 'gym',
    icon: '💪',
    mode: 'reps',
    camera: 'side',
    difficulty: 1,
    equipment: ['dumbbells'],
    muscles: ['brachioradialis', 'brachialis', 'biceps brachii'],
    summary: 'Curl dumbbells with a neutral, thumbs-up grip.',
    setup: [
      'Place camera side-on at chest height, 2 m away.',
      'Stand tall, dumbbells at sides, palms facing in.',
      'Keep elbows close to your torso.',
    ],
    met: 3.5,
    angles: [ELBOW, UPPER_ARM, TRUNK],
    reps: { driver: 'elbow', start: 'high', enter: 130, exit: 150, target: 60 },
    checks: [
      { angle: 'elbow', when: 'bottom', good: [30, 60], ok: [20, 75], cue: 'Curl all the way up', why: 'Full flexion loads the brachioradialis and brachialis fully.' },
      { angle: 'upperArm', when: 'any', good: [155, 180], ok: [140, 180], cue: 'Pin elbows to your sides', why: 'Elbows drifting forward shift work to the anterior deltoid.' },
      { angle: 'trunk', when: 'any', good: [0, 8], ok: [0, 15], cue: "Don't swing your torso", why: 'Torso swing adds momentum and reduces arm loading.' },
      { angle: 'elbow', when: 'top', good: [155, 180], ok: [145, 180], cue: 'Lower fully to straight arms', why: 'Full eccentric range builds strength at long muscle length.' },
    ],
  },
  {
    id: 'overhead-triceps-extension',
    name: 'Overhead Triceps Extension',
    category: 'gym',
    icon: '💪',
    mode: 'reps',
    camera: 'side',
    difficulty: 1,
    equipment: ['dumbbell'],
    muscles: ['triceps brachii'],
    summary: 'Hold a dumbbell overhead, lower it behind the head and extend.',
    setup: [
      'Place camera side-on at head height, 2 m away.',
      'Hold one dumbbell overhead with both hands.',
      'Keep upper arms vertical beside your ears.',
    ],
    met: 3.5,
    angles: [ELBOW, UPPER_ARM, TRUNK],
    reps: { driver: 'elbow', start: 'high', enter: 140, exit: 160, target: 70 },
    checks: [
      { angle: 'elbow', when: 'bottom', good: [30, 70], ok: [25, 90], cue: 'Lower weight fully behind head', why: 'Deep elbow flexion stretches the long head of the triceps.' },
      { angle: 'upperArm', when: 'any', good: [0, 25], ok: [0, 40], cue: 'Keep elbows pointing up', why: 'Elbows drifting forward turn the movement into a pullover.' },
      { angle: 'trunk', when: 'any', good: [0, 10], ok: [0, 20], cue: "Brace core, don't arch", why: 'Leaning back overhead loads the lumbar spine in extension.' },
    ],
  },
  {
    id: 'lateral-raise',
    name: 'Lateral Raise',
    category: 'gym',
    icon: '💪',
    mode: 'reps',
    camera: 'front',
    difficulty: 1,
    equipment: ['dumbbells'],
    muscles: ['lateral deltoids', 'supraspinatus', 'upper trapezius'],
    summary: 'Raise dumbbells out to the sides up to shoulder height.',
    setup: [
      'Place camera facing you at chest height, 2–3 m away.',
      'Stand tall, dumbbells at sides, slight elbow bend.',
    ],
    met: 3.5,
    angles: [SHOULDER_B, ELBOW_B, SHOULDERS_TILT],
    reps: { driver: 'shoulder', start: 'low', enter: 45, exit: 30, target: 80 },
    checks: [
      { angle: 'shoulder', when: 'bottom', good: [80, 100], ok: [65, 110], cue: 'Lift to shoulder height, no higher', why: 'Deltoid load peaks near 90°; higher shifts work to the traps.' },
      { ...levelShoulders, cue: 'Raise both arms evenly' },
    ],
  },
  {
    id: 'front-raise',
    name: 'Front Raise',
    category: 'gym',
    icon: '💪',
    mode: 'reps',
    camera: 'side',
    difficulty: 1,
    equipment: ['dumbbells or plate'],
    muscles: ['anterior deltoids', 'upper pectorals'],
    summary: 'Raise the weight straight in front to shoulder height.',
    setup: [
      'Place camera side-on at chest height, 2–3 m away.',
      'Stand tall, weights in front of thighs.',
    ],
    met: 3.5,
    angles: [SHOULDER, ELBOW, TRUNK],
    reps: { driver: 'shoulder', start: 'low', enter: 45, exit: 30, target: 80 },
    checks: [
      { angle: 'shoulder', when: 'bottom', good: [80, 105], ok: [65, 120], cue: 'Raise to shoulder height', why: 'Anterior deltoid moment arm peaks around 90° of flexion.' },
      { angle: 'elbow', when: 'any', good: [150, 180], ok: [135, 180], cue: 'Keep arms long, slight bend', why: 'Bent elbows shorten the lever and reduce load.' },
      { angle: 'trunk', when: 'any', good: [0, 8], ok: [0, 15], cue: "Don't lean back to swing", why: 'Leaning back uses momentum and stresses the lower back.' },
    ],
  },
  {
    id: 'forward-lunge',
    name: 'Forward Lunge',
    category: 'gym',
    icon: '🦵',
    mode: 'reps',
    camera: 'side',
    difficulty: 1,
    equipment: ['bodyweight', 'dumbbells optional'],
    muscles: ['quadriceps', 'glutes', 'hamstrings', 'adductors'],
    summary: 'Step forward, drop both knees to about 90° and push back to standing.',
    setup: [
      'Place camera side-on at hip height, 3 m away.',
      'Stand tall, feet hip-width, hands on hips.',
      'Alternate legs each rep.',
    ],
    met: 3.8, // 02022 calisthenics incl. lunges, moderate
    angles: [KNEE, HIP, TRUNK],
    reps: { driver: 'knee', start: 'high', enter: 145, exit: 160, target: 100, minRepMs: 800, alternating: true },
    checks: [
      { angle: 'knee', when: 'bottom', good: [75, 100], ok: [65, 115], cue: 'Drop until knees reach 90°', why: 'A ~90° lead knee is full lunge depth; patellofemoral load rises with flexion up to ~100° (Escamilla 2022 J Appl Biomech, doi:10.1123/jab.2021-0313).' },
      { angle: 'trunk', when: 'active', good: [0, 15], ok: [0, 25], cue: 'Keep torso upright', why: 'An upright torso keeps load on the legs and off the lower back.' },
      kneeLockout,
      hipLockout,
    ],
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    category: 'gym',
    icon: '🦵',
    mode: 'reps',
    camera: 'side',
    difficulty: 2,
    equipment: ['bench', 'dumbbells optional'],
    muscles: ['quadriceps', 'glutes', 'adductors'],
    summary: 'Rear foot on a bench, squat down on the front leg and drive up.',
    setup: [
      'Place camera side-on at hip height, 3 m away.',
      'Working leg nearest the camera, rear foot on bench.',
      'Front foot far enough that the knee stays over mid-foot.',
      'Turn around to film the other leg; keep the working leg nearest the camera.',
    ],
    met: 5.0, // 02052
    angles: [KNEE, TRUNK, SHIN],
    reps: { driver: 'knee', start: 'high', enter: 145, exit: 160, target: 95, minRepMs: 900 },
    checks: [
      { angle: 'knee', when: 'bottom', good: [0, 95], ok: [0, 110], cue: 'Lower until front thigh is parallel', why: 'Full depth maximises quad and glute work on the working leg.' },
      { angle: 'trunk', when: 'active', good: [0, 30], ok: [0, 40], cue: 'Keep chest up', why: 'Moderate lean is fine, but excess lean shifts load to the back.' },
      { angle: 'shin', when: 'bottom', good: [0, 35], ok: [0, 45], cue: 'Step front foot further forward', why: 'An excessive shin angle lifts the heel and overloads the knee.' },
      kneeLockout,
    ],
  },
  {
    id: 'hip-thrust',
    name: 'Hip Thrust',
    category: 'gym',
    icon: '🍑',
    mode: 'reps',
    camera: 'side',
    difficulty: 2,
    equipment: ['barbell', 'bench', 'pad'],
    muscles: ['glutes', 'hamstrings', 'quadriceps'],
    summary: 'Upper back on a bench, drive the barbell up with the hips to full extension.',
    setup: [
      'Place camera side-on at bench height, 2–3 m away.',
      'Upper back on bench edge, bar padded over hips.',
      'Feet flat, shins vertical at the top.',
    ],
    met: 3.5, // 02054
    angles: [HIP, KNEE, SHIN],
    reps: { driver: 'hip', start: 'low', enter: 140, exit: 120, target: 165, minRepMs: 800 },
    checks: [
      { angle: 'hip', when: 'bottom', good: [165, 180], ok: [150, 180], cue: 'Drive hips to full extension', why: 'Loaded hip extension to lockout is why the hip thrust out-activates the back squat for gluteus maximus (Contreras 2015 J Appl Biomech, doi:10.1123/jab.2014-0301).' },
      { angle: 'knee', when: 'bottom', good: [75, 105], ok: [65, 120], cue: 'Adjust feet, knees about 90°', why: 'A 90° knee at lockout balances glute and hamstring contribution.' },
      { angle: 'shin', when: 'bottom', good: [0, 15], ok: [0, 25], cue: 'Keep shins vertical at the top', why: 'Vertical shins keep tension on the glutes rather than quads.' },
    ],
  },
  {
    id: 'glute-bridge',
    name: 'Glute Bridge',
    category: 'gym',
    icon: '🍑',
    mode: 'reps',
    camera: 'side',
    difficulty: 1,
    equipment: ['mat'],
    muscles: ['glutes', 'hamstrings', 'core'],
    summary: 'Lying on the back with knees bent, lift the hips into a straight line.',
    setup: [
      'Place camera side-on at floor level, 2 m away.',
      'Lie on your back, knees bent, feet flat near glutes.',
      'Arms by your sides.',
    ],
    met: 3.0, // 02056 body-weight resistance, general
    angles: [HIP, KNEE, SHIN],
    reps: { driver: 'hip', start: 'low', enter: 155, exit: 140, target: 170 },
    checks: [
      { angle: 'hip', when: 'bottom', good: [165, 180], ok: [155, 180], cue: 'Lift hips higher, squeeze glutes', why: 'Full hip extension produces peak glute activation.' },
      { angle: 'knee', when: 'bottom', good: [70, 100], ok: [60, 115], cue: 'Set heels so knees are 90°', why: 'Feet too far out shifts the work to the hamstrings.' },
      { angle: 'shin', when: 'bottom', good: [0, 20], ok: [0, 30], cue: 'Keep shins vertical at the top', why: 'Vertical shins keep load on the glutes.' },
    ],
  },
  {
    id: 'standing-calf-raise',
    name: 'Standing Calf Raise',
    category: 'gym',
    icon: '🦶',
    mode: 'reps',
    camera: 'side',
    difficulty: 1,
    equipment: ['bodyweight', 'dumbbells optional'],
    muscles: ['gastrocnemius', 'soleus'],
    summary: 'Rise onto the balls of the feet with straight knees, then lower under control.',
    setup: [
      'Place camera side-on at ankle-to-knee height, 2 m away.',
      'Stand tall, feet hip-width, whole feet in frame.',
      'Hold a wall lightly for balance if needed.',
    ],
    met: 3.0, // 02056
    angles: [ANKLE, KNEE, TRUNK],
    reps: { driver: 'ankle', start: 'low', enter: 118, exit: 112, target: 125 },
    checks: [
      { angle: 'ankle', when: 'bottom', good: [125, 165], ok: [112, 170], cue: 'Rise higher onto the balls of feet', why: 'Full plantarflexion loads the calves through complete range. Flat-foot knee-ankle-toe reads about 104–110° (Winter anthropometry), so reps start above 118° and finish back below 112°.' },
      { angle: 'knee', when: 'any', good: [165, 180], ok: [155, 180], cue: 'Keep knees straight', why: 'Straight knees bias the gastrocnemius; bending adds momentum.' },
      { angle: 'trunk', when: 'any', good: [0, 8], ok: [0, 15], cue: "Stand tall, don't lean", why: 'Leaning shifts weight off the forefoot and shortens range.' },
    ],
  },
  {
    id: 'good-morning',
    name: 'Good Morning',
    category: 'gym',
    icon: '🏋️',
    mode: 'reps',
    camera: 'side',
    difficulty: 2,
    equipment: ['barbell'],
    muscles: ['hamstrings', 'glutes', 'erector spinae'],
    summary: 'Bar on the back, hinge at the hips until the torso nears parallel.',
    setup: [
      'Place camera side-on at hip height, 2–3 m away.',
      'Bar on upper back, feet hip-width, soft knees.',
      'Brace and keep the spine neutral.',
    ],
    met: 5.0, // 02052
    angles: [HIP, KNEE, TRUNK, SHIN],
    reps: { driver: 'hip', start: 'high', enter: 150, exit: 165, target: 110, minRepMs: 1000 },
    checks: [
      { angle: 'hip', when: 'bottom', good: [80, 110], ok: [70, 125], cue: 'Hinge until torso nearly parallel', why: 'Deep hinging loads the hamstrings through full range.' },
      { angle: 'trunk', when: 'bottom', good: [55, 95], ok: [45, 105], cue: 'Stop at parallel, back flat', why: 'Going below parallel under a back-loaded bar raises spinal shear.' },
      { angle: 'knee', when: 'active', good: [150, 180], ok: [135, 180], cue: "Soft knees, don't squat", why: 'Excess knee bend turns the hinge into a squat.' },
      { angle: 'shin', when: 'bottom', good: [0, 12], ok: [0, 20], cue: 'Push hips back, not knees forward', why: 'Forward knee travel reduces hamstring loading.' },
    ],
  },
  {
    id: 'upright-row',
    name: 'Upright Row',
    category: 'gym',
    icon: '💪',
    mode: 'reps',
    camera: 'front',
    difficulty: 1,
    equipment: ['barbell or dumbbells'],
    muscles: ['lateral deltoids', 'upper trapezius', 'biceps'],
    summary: 'Pull the weight up the body, leading with the elbows to shoulder height.',
    setup: [
      'Place camera facing you at chest height, 2–3 m away.',
      'Stand tall, grip at least shoulder-width.',
    ],
    met: 3.5,
    angles: [SHOULDER_B, HANDS, SHOULDERS_TILT],
    reps: { driver: 'shoulder', start: 'low', enter: 45, exit: 30, target: 75 },
    checks: [
      { angle: 'shoulder', when: 'bottom', good: [70, 95], ok: [60, 110], cue: 'Elbows to shoulder height, no higher', why: 'Raising the elbows above shoulder height increases impingement risk.' },
      { angle: 'hands', when: 'any', good: [0.9, 2.1], ok: [0.7, 2.4], cue: 'Grip at least shoulder-width', why: 'Deltoid and trapezius activity rise with grip width up to 2× shoulder breadth (McAllister 2013 JSCR, doi:10.1519/JSC.0b013e31824f23ad).' },
      levelShoulders,
    ],
  },
  {
    id: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    category: 'gym',
    icon: '🔔',
    mode: 'reps',
    camera: 'side',
    difficulty: 2,
    equipment: ['kettlebell'],
    muscles: ['glutes', 'hamstrings', 'erector spinae', 'core'],
    summary: 'Hinge and hike the bell back, then snap the hips to swing it to chest height.',
    setup: [
      'Place camera side-on at hip height, 3 m away.',
      'Feet slightly wider than hips, bell ahead of feet.',
      'Hike the bell back to start the first rep.',
    ],
    met: 9.8, // 02058 kettlebell swings
    angles: [HIP, KNEE, TRUNK],
    reps: { driver: 'hip', start: 'high', enter: 140, exit: 160, target: 110, minRepMs: 700 },
    checks: [
      { angle: 'hip', when: 'bottom', good: [60, 110], ok: [50, 125], cue: 'Hinge deeper, hike the bell back', why: 'A deep hinge loads the posterior chain for a powerful hip snap.' },
      { angle: 'knee', when: 'bottom', good: [120, 160], ok: [100, 170], cue: "Hinge, don't squat the swing", why: 'The hardstyle swing is hip-dominant with limited knee bend.' },
      hipLockout,
      { angle: 'trunk', when: 'top', good: [0, 10], ok: [0, 20], cue: "Stand tall, don't lean back", why: 'Leaning back at the top hyperextends the lumbar spine.' },
    ],
  },
  {
    id: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    category: 'gym',
    icon: '🏋️',
    mode: 'reps',
    camera: 'front',
    difficulty: 1,
    equipment: ['dumbbells', 'bench optional'],
    muscles: ['deltoids', 'triceps', 'upper trapezius'],
    summary: 'Press dumbbells from shoulder level to overhead lockout.',
    setup: [
      'Place camera facing you at chest height, 2–3 m away.',
      'Sit or stand tall, dumbbells at shoulder height.',
      'Forearms vertical, palms forward.',
    ],
    met: 3.5, // 02054
    angles: [SHOULDER_B, ELBOW_B, FOREARM_B, SHOULDERS_TILT],
    reps: { driver: 'shoulder', start: 'low', enter: 120, exit: 100, target: 160, minRepMs: 800 },
    checks: [
      { angle: 'shoulder', when: 'bottom', good: [160, 180], ok: [145, 180], cue: 'Press dumbbells fully overhead', why: 'Full shoulder elevation completes the pressing range.' },
      { angle: 'elbow', when: 'bottom', good: [160, 180], ok: [145, 180], cue: 'Lock out elbows at the top', why: 'Full extension ensures complete triceps and deltoid range.' },
      { angle: 'forearm', when: 'active', good: [0, 15], ok: [0, 25], cue: 'Keep forearms vertical under weights', why: 'Stacked forearms keep the load path efficient and protect the elbow.' },
      { ...levelShoulders, cue: 'Press both arms evenly' },
    ],
  },
];
