import type { ExerciseDef } from '../types.js';

/**
 * Sport-specific drills: athletics, throws/strikes, Olympic lifts.
 * Throws assume a right-handed athlete (block/front leg = left, near camera).
 */
export const SPORT: ExerciseDef[] = [
  // ─────────────────────────── ATHLETICS ───────────────────────────
  {
    id: 'sprint-start-set',
    name: 'Sprint Start — Set Position',
    category: 'athletics',
    icon: '🏁',
    mode: 'hold',
    camera: 'side',
    difficulty: 2,
    equipment: ['starting blocks (optional)'],
    muscles: ['quadriceps', 'glutes', 'hamstrings', 'shoulders'],
    summary: 'Hold the crouch-start "set" position with sprint-ready knee and hip angles.',
    setup: [
      'Place the camera side-on at hip height, 3 m away, on your LEFT side.',
      'Put your LEFT foot in the front block, right foot behind.',
      'Hands just behind the line, shoulder-width, arms straight.',
      'On "set", raise hips slightly above shoulders and hold.',
    ],
    met: 6.0,
    angles: [
      { id: 'frontKnee', label: 'Front knee', kind: 'joint', joint: 'knee', side: 'left' },
      { id: 'rearKnee', label: 'Rear knee', kind: 'joint', joint: 'knee', side: 'right' },
      { id: 'trunk', label: 'Trunk from vertical', kind: 'segment', segment: 'trunk', ref: 'vertical' },
      { id: 'upperArm', label: 'Arm from vertical', kind: 'segment', segment: 'upperArm', ref: 'vertical' },
      { id: 'elbow', label: 'Elbow', kind: 'joint', joint: 'elbow' },
    ],
    checks: [
      {
        angle: 'frontKnee', when: 'hold', good: [85, 100], ok: [78, 110],
        cue: 'Front knee near ninety degrees',
        why: 'A ~90° front knee in the set position is associated with higher block velocity (Mero 1988; Slawinski 2010).',
      },
      {
        angle: 'rearKnee', when: 'hold', good: [115, 140], ok: [105, 150],
        cue: 'Rear knee around one-thirty',
        why: 'A 120–135° rear knee lets the rear leg produce a fast, forceful first push.',
      },
      {
        angle: 'trunk', when: 'hold', good: [95, 112], ok: [88, 122],
        cue: 'Hips slightly above shoulders',
        why: 'Hips just above shoulders pre-loads the hips without over-stretching the hamstrings.',
      },
      {
        angle: 'upperArm', when: 'hold', good: [165, 180], ok: [150, 180],
        cue: 'Shoulders over or just ahead of hands',
        why: 'Vertical arms put the centre of mass forward for a rapid horizontal exit.',
      },
      {
        angle: 'elbow', when: 'hold', good: [165, 180], ok: [155, 180],
        cue: 'Lock arms straight',
        why: 'Straight arms keep the set position stable and repeatable.',
        weight: 0.5,
      },
    ],
    hold: { targetSec: 3 },
  },
  {
    id: 'high-knees',
    name: 'High Knees',
    category: 'athletics',
    icon: '🦵',
    mode: 'reps',
    camera: 'side',
    difficulty: 1,
    equipment: [],
    muscles: ['hip flexors', 'quadriceps', 'calves', 'core'],
    summary: 'Fast alternating knee drives to hip height with an upright trunk.',
    setup: [
      'Camera side-on at hip height, 3 m away, whole body in frame.',
      'Stand tall, arms bent about 90°.',
      'Drive each thigh up to hip height, staying on the balls of your feet.',
    ],
    met: 8.0,
    angles: [
      { id: 'thigh', label: 'Thigh from vertical', kind: 'segment', segment: 'thigh', ref: 'vertical' },
      { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee' },
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical' },
      { id: 'elbow', label: 'Elbow', kind: 'joint', joint: 'elbow' },
    ],
    checks: [
      {
        angle: 'thigh', when: 'bottom', good: [75, 100], ok: [70, 125],
        cue: 'Drive thigh to hip height',
        why: 'Thigh-parallel knee lift trains the hip-flexor range used in maximal sprinting.',
      },
      {
        angle: 'knee', when: 'bottom', good: [60, 100], ok: [50, 120],
        cue: 'Fold the lifted leg under',
        why: 'A flexed swing knee shortens the lever so the leg recovers faster.',
      },
      {
        angle: 'trunk', when: 'any', good: [0, 12], ok: [0, 20],
        cue: 'Stay tall, don\'t lean back',
        why: 'Leaning back to lift the knee shifts work from the hip flexors to the spine.',
      },
      {
        angle: 'elbow', when: 'active', good: [70, 110], ok: [55, 130],
        cue: 'Keep elbows bent near ninety',
        why: 'A ~90° arm swing counterbalances leg drive and sets cadence.',
        weight: 0.5,
      },
    ],
    reps: { driver: 'thigh', start: 'high', enter: 150, exit: 165, target: 100, minRepMs: 250, alternating: true },
  },
  {
    id: 'a-skip',
    name: 'A-Skip',
    category: 'athletics',
    icon: '👟',
    mode: 'reps',
    camera: 'side',
    difficulty: 2,
    equipment: [],
    muscles: ['hip flexors', 'calves', 'glutes', 'hamstrings'],
    summary: 'Rhythmic skip with a high knee, dorsiflexed foot and active down-strike.',
    setup: [
      'Camera side-on at hip height, 4 m away; skip across the frame.',
      'Lift the knee to hip height with toes pulled up.',
      'Strike the ground under your hips, then switch legs.',
    ],
    met: 8.0,
    angles: [
      { id: 'thigh', label: 'Thigh from vertical', kind: 'segment', segment: 'thigh', ref: 'vertical' },
      { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee' },
      { id: 'ankle', label: 'Ankle', kind: 'joint', joint: 'ankle' },
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical' },
    ],
    checks: [
      {
        angle: 'thigh', when: 'bottom', good: [75, 100], ok: [70, 125],
        cue: 'Knee up to hip height',
        why: 'Hip-height knee lift rehearses the front-side mechanics of upright sprinting.',
      },
      {
        angle: 'knee', when: 'bottom', good: [70, 100], ok: [55, 120],
        cue: 'Shin vertical under the knee',
        why: 'A vertical shin at peak lift positions the foot to strike under the hips.',
      },
      {
        angle: 'ankle', when: 'bottom', good: [70, 95], ok: [60, 105],
        cue: 'Toes up, foot dorsiflexed',
        why: 'A dorsiflexed ankle stiffens the foot for a short, reactive ground contact.',
      },
      {
        angle: 'trunk', when: 'any', good: [0, 12], ok: [0, 20],
        cue: 'Tall posture, hips tall',
        why: 'An upright trunk keeps the pelvis neutral so the hip flexors can work through range.',
      },
    ],
    reps: { driver: 'thigh', start: 'high', enter: 150, exit: 165, target: 100, minRepMs: 350, alternating: true },
  },
  {
    id: 'butt-kicks',
    name: 'Butt Kicks',
    category: 'athletics',
    icon: '🔁',
    mode: 'reps',
    camera: 'side',
    difficulty: 1,
    equipment: [],
    muscles: ['hamstrings', 'quadriceps', 'calves'],
    summary: 'Quick alternating heel pulls toward the glutes with knees pointing down.',
    setup: [
      'Camera side-on at hip height, 3 m away, whole body in frame.',
      'Jog in place on the balls of your feet.',
      'Snap each heel up to your glutes, knee pointing at the floor.',
    ],
    met: 8.0,
    angles: [
      { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee' },
      { id: 'thigh', label: 'Thigh from vertical', kind: 'segment', segment: 'thigh', ref: 'vertical' },
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical' },
    ],
    checks: [
      {
        angle: 'knee', when: 'bottom', good: [25, 55], ok: [25, 75],
        cue: 'Heel all the way to glute',
        why: 'Full knee flexion rehearses the short recovery lever of fast sprinting.',
      },
      {
        angle: 'thigh', when: 'bottom', good: [150, 180], ok: [135, 180],
        cue: 'Keep knee pointing down',
        why: 'A vertical thigh isolates hamstring action instead of turning it into a high-knee.',
      },
      {
        angle: 'trunk', when: 'any', good: [0, 12], ok: [0, 20],
        cue: 'Stay tall through the trunk',
        why: 'Upright posture keeps the drill specific to sprint mechanics.',
      },
    ],
    reps: { driver: 'knee', start: 'high', enter: 140, exit: 160, target: 55, minRepMs: 250, alternating: true },
  },
  {
    id: 'countermovement-jump',
    name: 'Countermovement Jump',
    category: 'athletics',
    icon: '🚀',
    mode: 'event',
    camera: 'side',
    difficulty: 1,
    equipment: [],
    muscles: ['quadriceps', 'glutes', 'calves', 'hamstrings'],
    summary: 'Quick dip and maximal vertical jump — flight time gives jump height.',
    setup: [
      'Camera side-on at hip height, 3 m away, head-to-toe plus space above.',
      'Stand tall, feet hip-width.',
      'Dip fast to a comfortable depth, swing arms and jump straight up.',
      'Land in the same spot.',
    ],
    met: 8.0,
    angles: [
      { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee' },
      { id: 'hip', label: 'Hip', kind: 'joint', joint: 'hip' },
      { id: 'ankle', label: 'Ankle', kind: 'joint', joint: 'ankle' },
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical' },
    ],
    checks: [
      {
        angle: 'knee', when: 'bottom', good: [80, 110], ok: [65, 130],
        cue: 'Dip to about quarter-to-half squat',
        why: 'Self-selected CMJ depths of ~90–110° knee angle maximise jump height (Gheller 2015).',
      },
      {
        angle: 'trunk', when: 'bottom', good: [20, 50], ok: [10, 60],
        cue: 'Chest up in the dip',
        why: 'Excess forward lean moves load to the lower back and wastes hip drive.',
      },
      {
        angle: 'knee', when: 'release', good: [165, 180], ok: [155, 180],
        cue: 'Fully straighten knees at take-off',
        why: 'Incomplete knee extension at take-off directly reduces take-off velocity.',
      },
      {
        angle: 'hip', when: 'release', good: [165, 180], ok: [150, 180],
        cue: 'Drive hips through to tall',
        why: 'Full hip extension is the largest contributor to vertical jump power.',
      },
      {
        angle: 'ankle', when: 'release', good: [115, 160], ok: [105, 170],
        cue: 'Push off through the toes',
        why: 'Ankle plantarflexion completes triple extension and adds final take-off velocity.',
      },
    ],
    event: { trigger: 'jump' },
  },
  {
    id: 'squat-jump',
    name: 'Squat Jump (Static Start)',
    category: 'athletics',
    icon: '🐸',
    mode: 'event',
    camera: 'side',
    difficulty: 1,
    equipment: [],
    muscles: ['quadriceps', 'glutes', 'calves'],
    summary: 'Jump from a paused 90° squat with no dip, testing concentric power.',
    setup: [
      'Camera side-on at hip height, 3 m away, space above head in frame.',
      'Hands on hips, squat to 90° knees and pause 2 s.',
      'Jump straight up without dipping further.',
    ],
    met: 8.0,
    angles: [
      { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee' },
      { id: 'hip', label: 'Hip', kind: 'joint', joint: 'hip' },
      { id: 'ankle', label: 'Ankle', kind: 'joint', joint: 'ankle' },
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical' },
    ],
    checks: [
      {
        angle: 'knee', when: 'bottom', good: [85, 100], ok: [75, 110],
        cue: 'Start from a ninety degree squat',
        why: 'The standard squat-jump protocol uses a 90° knee start for comparable results.',
      },
      {
        angle: 'trunk', when: 'bottom', good: [20, 45], ok: [10, 55],
        cue: 'Keep chest up in the squat',
        why: 'A consistent trunk angle keeps the test repeatable and protects the spine.',
      },
      {
        angle: 'knee', when: 'release', good: [165, 180], ok: [155, 180],
        cue: 'Straighten knees fully at take-off',
        why: 'Full knee extension at take-off maximises take-off velocity.',
      },
      {
        angle: 'hip', when: 'release', good: [165, 180], ok: [150, 180],
        cue: 'Drive hips up to tall',
        why: 'Hip extension is the main power source in a no-countermovement jump.',
      },
      {
        angle: 'ankle', when: 'release', good: [115, 160], ok: [105, 170],
        cue: 'Finish on your toes',
        why: 'Plantarflexion completes triple extension at take-off.',
      },
    ],
    event: { trigger: 'jump' },
  },
  {
    id: 'standing-broad-jump',
    name: 'Standing Broad Jump',
    category: 'athletics',
    icon: '📏',
    mode: 'event',
    camera: 'side',
    difficulty: 2,
    equipment: [],
    muscles: ['glutes', 'quadriceps', 'hamstrings', 'calves'],
    summary: 'Two-foot horizontal jump for distance with a strong arm swing.',
    setup: [
      'Camera side-on at hip height, 5 m away; jump across the frame.',
      'Toes behind the line, feet hip-width.',
      'Swing arms back, dip, then drive arms forward and jump out.',
      'Stick the landing on both feet.',
    ],
    met: 8.0,
    angles: [
      { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee' },
      { id: 'hip', label: 'Hip', kind: 'joint', joint: 'hip' },
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical' },
      { id: 'shoulder', label: 'Arm swing', kind: 'joint', joint: 'shoulder' },
    ],
    checks: [
      {
        angle: 'knee', when: 'bottom', good: [70, 110], ok: [60, 130],
        cue: 'Load deeper before jumping',
        why: 'A deep, fast countermovement stores elastic energy for horizontal drive.',
      },
      {
        angle: 'knee', when: 'release', good: [160, 180], ok: [150, 180],
        cue: 'Extend knees fully at take-off',
        why: 'Complete knee extension at take-off increases take-off velocity and distance.',
      },
      {
        angle: 'hip', when: 'release', good: [160, 180], ok: [145, 180],
        cue: 'Drive hips forward through take-off',
        why: 'Hip extension is the dominant joint contributor in standing long jump.',
      },
      {
        angle: 'trunk', when: 'release', good: [30, 55], ok: [20, 65],
        cue: 'Lean forward into the jump',
        why: 'A forward body lean at take-off directs the push horizontally.',
      },
      {
        angle: 'shoulder', when: 'release', good: [120, 180], ok: [90, 180],
        cue: 'Swing arms forward and up',
        why: 'An arm swing adds ~20% to standing jump distance (Ashby & Heegaard 2002).',
      },
    ],
    event: { trigger: 'jump', releaseAngle: { good: [28, 42], ok: [18, 52] } },
  },
  {
    id: 'box-jump',
    name: 'Box Jump',
    category: 'athletics',
    icon: '📦',
    mode: 'event',
    camera: 'side',
    difficulty: 2,
    equipment: ['plyo box'],
    muscles: ['quadriceps', 'glutes', 'calves', 'hamstrings'],
    summary: 'Explosive jump onto a box with full triple extension at take-off.',
    setup: [
      'Box in front of you; camera side-on at hip height, box and you in frame.',
      'Stand one step from the box, feet hip-width.',
      'Dip, swing arms and jump, landing softly on the box.',
      'Step down; do not jump down.',
    ],
    met: 8.0,
    angles: [
      { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee' },
      { id: 'hip', label: 'Hip', kind: 'joint', joint: 'hip' },
      { id: 'shoulder', label: 'Arm swing', kind: 'joint', joint: 'shoulder' },
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical' },
    ],
    checks: [
      {
        angle: 'knee', when: 'bottom', good: [80, 115], ok: [65, 135],
        cue: 'Load with a quick quarter squat',
        why: 'A moderate, fast countermovement maximises take-off power.',
      },
      {
        angle: 'trunk', when: 'bottom', good: [20, 50], ok: [10, 60],
        cue: 'Chest up as you load',
        why: 'Excess trunk flexion in the dip wastes hip drive and loads the spine.',
      },
      {
        angle: 'knee', when: 'release', good: [160, 180], ok: [150, 180],
        cue: 'Straighten legs fully before tucking',
        why: 'Tucking before full extension inflates box height while reducing actual jump power.',
      },
      {
        angle: 'hip', when: 'release', good: [160, 180], ok: [145, 180],
        cue: 'Drive hips through at take-off',
        why: 'Full hip extension produces most of the vertical impulse.',
      },
      {
        angle: 'shoulder', when: 'release', good: [110, 180], ok: [80, 180],
        cue: 'Swing arms up hard',
        why: 'An arm swing increases vertical jump height by roughly 10%.',
        weight: 0.5,
      },
    ],
    event: { trigger: 'jump' },
  },
  {
    id: 'lateral-bound',
    name: 'Lateral Bound',
    category: 'athletics',
    icon: '🦘',
    mode: 'reps',
    camera: 'front',
    difficulty: 2,
    equipment: [],
    muscles: ['glutes', 'adductors', 'quadriceps', 'calves'],
    summary: 'Side-to-side single-leg bounds, sticking each landing with a level pelvis.',
    setup: [
      'Camera facing you at hip height, 4 m away, with room either side.',
      'Balance on one leg, then bound sideways onto the other.',
      'Stick each landing for a moment, then bound back.',
    ],
    met: 8.0,
    angles: [
      { id: 'feet', label: 'Foot spread', kind: 'spread', what: 'feet' },
      { id: 'shoulders', label: 'Shoulder tilt', kind: 'segment', segment: 'shoulders', ref: 'horizontal' },
      { id: 'hips', label: 'Hip tilt', kind: 'segment', segment: 'hips', ref: 'horizontal' },
      { id: 'trunk', label: 'Trunk side lean', kind: 'segment', segment: 'trunk', ref: 'vertical' },
    ],
    checks: [
      {
        angle: 'feet', when: 'bottom', good: [2.0, 5.0], ok: [1.4, 5.0],
        cue: 'Push farther sideways',
        why: 'Lateral bound distance reflects frontal-plane hip power used in cutting.',
      },
      {
        angle: 'hips', when: 'top', good: [0, 8], ok: [0, 15],
        cue: 'Keep hips level on landing',
        why: 'Pelvic drop on single-leg landing signals weak hip abductors and raises knee-valgus risk.',
      },
      {
        angle: 'shoulders', when: 'top', good: [0, 8], ok: [0, 15],
        cue: 'Keep shoulders level',
        why: 'Large shoulder tilt on landing indicates poor trunk control.',
      },
      {
        angle: 'trunk', when: 'active', good: [0, 15], ok: [0, 25],
        cue: 'Stay stacked over the stance leg',
        why: 'Excess lateral trunk lean is a known ACL-injury risk factor in landing tasks (Hewett 2009).',
      },
    ],
    reps: { driver: 'feet', start: 'low', enter: 1.3, exit: 0.9, target: 2.0, minRepMs: 500 },
  },

  // ─────────────────────────── THROWS / STRIKES ───────────────────────────
  {
    id: 'javelin-release',
    name: 'Javelin Release',
    category: 'throws',
    icon: '🎯',
    mode: 'event',
    camera: 'side',
    difficulty: 3,
    equipment: ['javelin (or towel/turbo jav)'],
    muscles: ['lats', 'shoulders', 'core', 'quadriceps'],
    summary: 'Block, brace and release over a straight front leg at the optimal angle.',
    setup: [
      'Right-handed: camera side-on on your LEFT, 6 m away, full body in frame.',
      'Run in or step into the throw across the frame.',
      'Plant the left leg, stay tall, throw over the top.',
    ],
    met: 6.0,
    angles: [
      { id: 'blockKnee', label: 'Block (left) knee', kind: 'joint', joint: 'knee', side: 'left' },
      { id: 'shoulder', label: 'Throwing shoulder', kind: 'joint', joint: 'shoulder', side: 'right' },
      { id: 'elbow', label: 'Throwing elbow', kind: 'joint', joint: 'elbow', side: 'right' },
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical' },
    ],
    checks: [
      {
        angle: 'blockKnee', when: 'release', good: [160, 180], ok: [145, 180],
        cue: 'Brace the block leg straight',
        why: 'Elite throwers keep the block knee ≥160° at release, converting run-up speed into release speed (Bartlett 1996).',
        weight: 1.5,
      },
      {
        angle: 'shoulder', when: 'release', good: [120, 170], ok: [100, 180],
        cue: 'Throwing elbow high above shoulder',
        why: 'A high elbow keeps the throw over the top and protects the elbow from valgus stress.',
      },
      {
        angle: 'elbow', when: 'release', good: [150, 180], ok: [130, 180],
        cue: 'Extend the arm through release',
        why: 'A long arm at release lengthens the acceleration path.',
      },
      {
        angle: 'trunk', when: 'release', good: [0, 25], ok: [0, 40],
        cue: 'Throw over a tall block',
        why: 'Collapsing forward at release shortens the pull and lowers release height.',
      },
    ],
    event: { trigger: 'wristPeak', releaseAngle: { good: [32, 38], ok: [26, 44] } },
  },
  {
    id: 'shot-put',
    name: 'Shot Put',
    category: 'throws',
    icon: '⚫',
    mode: 'event',
    camera: 'side',
    difficulty: 2,
    equipment: ['shot (or medicine ball)'],
    muscles: ['triceps', 'chest', 'shoulders', 'quadriceps', 'glutes'],
    summary: 'Put the shot with full leg drive and a high, extended release.',
    setup: [
      'Right-handed: camera side-on on your LEFT, 5 m away, full body in frame.',
      'Shot on the neck, elbow high, facing across the frame.',
      'Drive legs, extend and punch the shot out at release.',
    ],
    met: 4.0,
    angles: [
      { id: 'elbow', label: 'Putting elbow', kind: 'joint', joint: 'elbow', side: 'right' },
      { id: 'shoulder', label: 'Putting shoulder', kind: 'joint', joint: 'shoulder', side: 'right' },
      { id: 'frontKnee', label: 'Front (left) knee', kind: 'joint', joint: 'knee', side: 'left' },
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical' },
    ],
    checks: [
      {
        angle: 'elbow', when: 'release', good: [160, 180], ok: [150, 180],
        cue: 'Punch the arm fully straight',
        why: 'An elbow ≥150° at release maximises release height and speed.',
        weight: 1.5,
      },
      {
        angle: 'shoulder', when: 'release', good: [90, 135], ok: [75, 150],
        cue: 'Release above shoulder height',
        why: 'Release height is a key determinant of shot distance.',
      },
      {
        angle: 'frontKnee', when: 'release', good: [155, 180], ok: [140, 180],
        cue: 'Block and extend the front leg',
        why: 'Extending the front leg at release lifts the release point and transfers momentum.',
      },
      {
        angle: 'trunk', when: 'release', good: [0, 25], ok: [0, 40],
        cue: 'Finish tall, chest up',
        why: 'A tall finish keeps release height up and the push directed upward-forward.',
      },
    ],
    event: { trigger: 'wristPeak', releaseAngle: { good: [35, 42], ok: [30, 46] } },
  },
  {
    id: 'discus-release',
    name: 'Discus Release',
    category: 'throws',
    icon: '🥏',
    mode: 'event',
    camera: 'side',
    difficulty: 3,
    equipment: ['discus (or cone)'],
    muscles: ['chest', 'shoulders', 'obliques', 'glutes'],
    summary: 'Sling the discus at shoulder height with a long arm over a braced left leg.',
    setup: [
      'Right-handed: camera side-on on your LEFT, 6 m away, full body in frame.',
      'Use a standing throw or turn, releasing across the frame.',
      'Keep the throwing arm long and at shoulder height.',
    ],
    met: 4.0,
    angles: [
      { id: 'shoulder', label: 'Throwing shoulder', kind: 'joint', joint: 'shoulder', side: 'right' },
      { id: 'elbow', label: 'Throwing elbow', kind: 'joint', joint: 'elbow', side: 'right' },
      { id: 'blockKnee', label: 'Block (left) knee', kind: 'joint', joint: 'knee', side: 'left' },
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical' },
    ],
    checks: [
      {
        angle: 'shoulder', when: 'release', good: [80, 110], ok: [65, 125],
        cue: 'Release at shoulder height',
        why: 'A shoulder-height arm gives the longest radius and a flat release path.',
      },
      {
        angle: 'elbow', when: 'release', good: [160, 180], ok: [145, 180],
        cue: 'Keep the throwing arm long',
        why: 'A long arm increases the radius and linear release speed of the discus.',
      },
      {
        angle: 'blockKnee', when: 'release', good: [150, 180], ok: [135, 180],
        cue: 'Brace the left leg',
        why: 'A firm left-side block stops rotation and transfers it into the implement.',
      },
      {
        angle: 'trunk', when: 'release', good: [0, 20], ok: [0, 35],
        cue: 'Stay tall through release',
        why: 'Bending over at release lowers release height and angle.',
      },
    ],
    event: { trigger: 'wristPeak', releaseAngle: { good: [35, 40], ok: [30, 45] } },
  },
  {
    id: 'fast-bowling-delivery',
    name: 'Cricket Fast Bowling Delivery',
    category: 'throws',
    icon: '🏏',
    mode: 'event',
    camera: 'side',
    difficulty: 3,
    equipment: ['cricket ball'],
    muscles: ['shoulders', 'lats', 'obliques', 'quadriceps'],
    summary: 'Deliver over a braced front knee with a high, straight bowling arm.',
    setup: [
      'Right-arm bowler: camera side-on on your LEFT at hip height, 8 m away.',
      'Run in and bowl across the frame.',
      'Land the front foot, brace the knee and bowl over the top.',
    ],
    met: 4.8,
    angles: [
      { id: 'frontKnee', label: 'Front (left) knee', kind: 'joint', joint: 'knee', side: 'left' },
      { id: 'elbow', label: 'Bowling elbow', kind: 'joint', joint: 'elbow', side: 'right' },
      { id: 'shoulder', label: 'Bowling shoulder', kind: 'joint', joint: 'shoulder', side: 'right' },
      { id: 'trunk', label: 'Trunk flexion', kind: 'segment', segment: 'trunk', ref: 'vertical' },
    ],
    checks: [
      {
        angle: 'frontKnee', when: 'release', good: [165, 180], ok: [150, 180],
        cue: 'Brace the front knee straight',
        why: 'A braced front knee at ball release is linked to higher ball speed (Portus 2004; Worthington 2013).',
        weight: 1.5,
      },
      {
        angle: 'elbow', when: 'release', good: [165, 180], ok: [155, 180],
        cue: 'Keep the bowling arm straight',
        why: 'ICC law allows ≤15° elbow extension; an elbow near straight at release keeps the action legal (2D screen only, not a legality test).',
        weight: 1.5,
      },
      {
        angle: 'shoulder', when: 'release', good: [150, 180], ok: [135, 180],
        cue: 'Release with arm near vertical',
        why: 'A high arm at release maximises release height and bounce.',
      },
      {
        angle: 'trunk', when: 'release', good: [10, 35], ok: [0, 45],
        cue: 'Drive chest over the front leg',
        why: 'Forward trunk flexion at release contributes to ball speed.',
      },
    ],
    event: { trigger: 'wristPeak' },
  },
  {
    id: 'basketball-jump-shot',
    name: 'Basketball Jump Shot',
    category: 'throws',
    icon: '🏀',
    mode: 'event',
    camera: 'side',
    difficulty: 2,
    equipment: ['basketball'],
    muscles: ['triceps', 'shoulders', 'quadriceps', 'calves'],
    summary: 'Jump, extend and release at the top with a high arc.',
    setup: [
      'Camera side-on on your shooting-arm side, 4 m away, full body plus ball in frame.',
      'Shoot toward the edge of the frame.',
      'Jump straight up and release near the top.',
    ],
    met: 4.5,
    angles: [
      { id: 'elbow', label: 'Shooting elbow', kind: 'joint', joint: 'elbow' },
      { id: 'shoulder', label: 'Shooting shoulder', kind: 'joint', joint: 'shoulder' },
      { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee' },
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical' },
    ],
    checks: [
      {
        angle: 'elbow', when: 'release', good: [155, 180], ok: [140, 180],
        cue: 'Extend the elbow, snap the wrist',
        why: 'Full elbow extension at release gives a consistent, high release point.',
      },
      {
        angle: 'shoulder', when: 'release', good: [130, 170], ok: [110, 180],
        cue: 'Release high above your head',
        why: 'A high release point reduces the chance of being blocked and flattens less.',
      },
      {
        angle: 'knee', when: 'release', good: [160, 180], ok: [145, 180],
        cue: 'Release at the top, legs extended',
        why: 'Releasing at peak jump height with legs extended improves shot consistency (Okazaki 2015).',
      },
      {
        angle: 'trunk', when: 'release', good: [0, 12], ok: [0, 20],
        cue: 'Jump straight up, don\'t drift',
        why: 'Leaning or drifting in the air changes release conditions shot to shot.',
      },
    ],
    event: { trigger: 'wristPeak', releaseAngle: { good: [45, 55], ok: [38, 62] } },
  },
  {
    id: 'overhead-smash',
    name: 'Overhead Smash (Badminton/Tennis)',
    category: 'throws',
    icon: '🏸',
    mode: 'event',
    camera: 'side',
    difficulty: 2,
    equipment: ['racket'],
    muscles: ['shoulders', 'triceps', 'lats', 'obliques'],
    summary: 'Hit at full reach above and in front of the head with an extended arm.',
    setup: [
      'Camera side-on on your racket-arm side, 4 m away, full body and racket in frame.',
      'Start side-on, racket up behind the head.',
      'Reach and strike at the highest point in front of you.',
    ],
    met: 7.0,
    angles: [
      { id: 'elbow', label: 'Hitting elbow', kind: 'joint', joint: 'elbow' },
      { id: 'shoulder', label: 'Hitting shoulder', kind: 'joint', joint: 'shoulder' },
      { id: 'upperArm', label: 'Upper arm from vertical', kind: 'segment', segment: 'upperArm', ref: 'vertical' },
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical' },
    ],
    checks: [
      {
        angle: 'elbow', when: 'release', good: [155, 180], ok: [140, 180],
        cue: 'Hit at full arm extension',
        why: 'Contact with an extended elbow gives maximal height and racket-head speed.',
      },
      {
        angle: 'shoulder', when: 'release', good: [150, 180], ok: [130, 180],
        cue: 'Contact high above your head',
        why: 'A high contact point steepens the shot angle and increases winners.',
      },
      {
        angle: 'upperArm', when: 'release', good: [0, 30], ok: [0, 45],
        cue: 'Reach up, contact slightly in front',
        why: 'Upper arm near vertical at contact keeps the strike over the top and protects the shoulder.',
      },
      {
        angle: 'trunk', when: 'release', good: [0, 25], ok: [0, 35],
        cue: 'Stay tall through contact',
        why: 'Bending at the waist before contact lowers the hitting point.',
        weight: 0.5,
      },
    ],
    event: { trigger: 'wristPeak' },
  },
  {
    id: 'boxing-straight-punch',
    name: 'Boxing Straight Punch',
    category: 'throws',
    icon: '🥊',
    mode: 'event',
    camera: 'side',
    difficulty: 1,
    equipment: ['gloves (optional)'],
    muscles: ['triceps', 'chest', 'shoulders', 'obliques'],
    summary: 'Straight punch at shoulder height with full extension and a stable base.',
    setup: [
      'Camera side-on on your punching-arm side, 3 m away, full body in frame.',
      'Guard up, feet staggered, knees soft.',
      'Punch straight out at shoulder height and snap back.',
    ],
    met: 5.5,
    angles: [
      { id: 'elbow', label: 'Punching elbow', kind: 'joint', joint: 'elbow' },
      { id: 'shoulder', label: 'Punching shoulder', kind: 'joint', joint: 'shoulder' },
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical' },
      { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee' },
    ],
    checks: [
      {
        angle: 'elbow', when: 'release', good: [160, 180], ok: [150, 180],
        cue: 'Extend fully through the target',
        why: 'Peak fist speed occurs near full elbow extension in straight punches.',
      },
      {
        angle: 'shoulder', when: 'release', good: [80, 100], ok: [70, 110],
        cue: 'Punch at shoulder height',
        why: 'A horizontal arm line delivers force straight into the target.',
      },
      {
        angle: 'trunk', when: 'release', good: [0, 15], ok: [0, 25],
        cue: 'Don\'t lunge, stay over feet',
        why: 'Over-leaning costs balance and leaves you open to counters.',
      },
      {
        angle: 'knee', when: 'release', good: [140, 172], ok: [130, 180],
        cue: 'Keep knees soft',
        why: 'Slightly flexed knees let leg drive contribute to punch force.',
        weight: 0.5,
      },
    ],
    event: { trigger: 'wristPeak' },
  },

  // ─────────────────────────── OLYMPIC LIFTS ───────────────────────────
  {
    id: 'power-clean',
    name: 'Power Clean',
    category: 'olympic',
    icon: '🏋️',
    mode: 'reps',
    camera: 'side',
    difficulty: 3,
    equipment: ['barbell', 'plates'],
    muscles: ['glutes', 'hamstrings', 'quadriceps', 'traps', 'calves'],
    summary: 'Pull from the floor to full triple extension, catch high in the front rack.',
    setup: [
      'Camera side-on at hip height, 3–4 m away, bar and full body in frame.',
      'Bar over mid-foot, hips above knees, back flat, arms long.',
      'Extend explosively, pull under, catch above parallel.',
      'Return the bar to the floor between reps.',
    ],
    met: 6.0,
    angles: [
      { id: 'hip', label: 'Hip', kind: 'joint', joint: 'hip' },
      { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee' },
      { id: 'trunk', label: 'Back angle', kind: 'segment', segment: 'trunk', ref: 'vertical' },
      { id: 'elbow', label: 'Elbow', kind: 'joint', joint: 'elbow' },
    ],
    checks: [
      {
        angle: 'hip', when: 'bottom', good: [170, 180], ok: [160, 180],
        cue: 'Finish the hips — full extension',
        why: 'Complete hip extension in the second pull generates peak bar power (Garhammer 1993).',
        weight: 1.5,
      },
      {
        angle: 'knee', when: 'bottom', good: [165, 180], ok: [150, 180],
        cue: 'Straighten the knees at the top',
        why: 'Full knee extension completes triple extension before pulling under.',
      },
      {
        angle: 'trunk', when: 'top', good: [40, 70], ok: [30, 80],
        cue: 'Shoulders over the bar at start',
        why: 'A 40–70° back angle with shoulders over the bar sets an efficient first pull.',
      },
      {
        angle: 'elbow', when: 'top', good: [160, 180], ok: [150, 180],
        cue: 'Arms long, don\'t pull early',
        why: 'Early arm bend reduces force transfer from the legs and hips.',
      },
    ],
    // Hip flexed at the floor (~45–80°) → full extension (~180°); catch (~100–115°) stays above exit.
    reps: { driver: 'hip', start: 'low', enter: 120, exit: 95, target: 170, minRepMs: 1200 },
  },
  {
    id: 'hang-clean',
    name: 'Hang Power Clean',
    category: 'olympic',
    icon: '🪝',
    mode: 'reps',
    camera: 'side',
    difficulty: 3,
    equipment: ['barbell', 'plates'],
    muscles: ['glutes', 'hamstrings', 'traps', 'quadriceps'],
    summary: 'From mid-thigh hang, extend and catch the bar in a high-elbow front rack.',
    setup: [
      'Camera side-on at hip height, 3 m away, bar and full body in frame.',
      'Stand tall, hinge until the bar is at mid-thigh, arms long.',
      'Extend, pull under and catch with elbows high.',
      'Lower the bar back to the hang between reps.',
    ],
    met: 6.0,
    angles: [
      { id: 'elbow', label: 'Elbow', kind: 'joint', joint: 'elbow' },
      { id: 'upperArm', label: 'Elbow height (upper arm)', kind: 'segment', segment: 'upperArm', ref: 'vertical' },
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical' },
      { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee' },
    ],
    checks: [
      {
        angle: 'elbow', when: 'bottom', good: [20, 60], ok: [20, 80],
        cue: 'Rack the bar on your shoulders',
        why: 'A fully flexed elbow means the bar is racked on the shoulders, not held by the arms.',
      },
      {
        angle: 'upperArm', when: 'bottom', good: [65, 110], ok: [50, 125],
        cue: 'Elbows up in the catch',
        why: 'High elbows keep the bar on the shoulders and the trunk upright.',
        weight: 1.5,
      },
      {
        angle: 'trunk', when: 'bottom', good: [0, 20], ok: [0, 30],
        cue: 'Catch with chest tall',
        why: 'An upright catch keeps the bar over mid-foot and spares the lower back.',
      },
      {
        angle: 'knee', when: 'bottom', good: [100, 180], ok: [85, 180],
        cue: 'Receive above parallel',
        why: 'A power catch is received with thighs above parallel.',
        weight: 0.5,
      },
      {
        angle: 'elbow', when: 'top', good: [160, 180], ok: [145, 180],
        cue: 'Arms long until full extension',
        why: 'Bending the arms early is the most common hang-clean fault and bleeds leg power.',
      },
    ],
    // Elbow driver: one straight→rack→straight cycle per rep, immune to the hip/knee dip-and-catch double peaks.
    reps: { driver: 'elbow', start: 'high', enter: 120, exit: 150, target: 60, minRepMs: 1000 },
  },
  {
    id: 'snatch',
    name: 'Snatch',
    category: 'olympic',
    icon: '⚡',
    mode: 'reps',
    camera: 'side',
    difficulty: 3,
    equipment: ['barbell', 'plates'],
    muscles: ['glutes', 'hamstrings', 'traps', 'shoulders', 'quadriceps'],
    summary: 'Wide-grip pull from the floor to an overhead-squat catch with locked arms.',
    setup: [
      'Camera side-on at hip height, 4 m away, bar overhead must stay in frame.',
      'Wide grip, bar over mid-foot, arms long.',
      'Extend, pull under and catch in an overhead squat.',
      'Stand up with the bar locked overhead, then lower it.',
    ],
    met: 6.0,
    angles: [
      { id: 'shoulder', label: 'Shoulder (arm elevation)', kind: 'joint', joint: 'shoulder' },
      { id: 'elbow', label: 'Elbow', kind: 'joint', joint: 'elbow' },
      { id: 'upperArm', label: 'Arm from vertical', kind: 'segment', segment: 'upperArm', ref: 'vertical' },
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical' },
    ],
    checks: [
      {
        angle: 'shoulder', when: 'bottom', good: [165, 180], ok: [150, 180],
        cue: 'Push the bar fully overhead',
        why: 'Full shoulder flexion stacks the bar over the trunk in the overhead catch.',
      },
      {
        angle: 'elbow', when: 'bottom', good: [165, 180], ok: [155, 180],
        cue: 'Lock the elbows hard',
        why: 'Soft elbows in the catch are a common cause of missed snatches and a press-out no-lift.',
        weight: 1.5,
      },
      {
        angle: 'upperArm', when: 'bottom', good: [0, 20], ok: [0, 30],
        cue: 'Bar over the back of your neck',
        why: 'Vertical arms keep the bar over mid-foot so the overhead squat is balanced.',
      },
      {
        angle: 'trunk', when: 'bottom', good: [0, 30], ok: [0, 45],
        cue: 'Chest up in the catch',
        why: 'Excessive forward lean pushes the bar ahead of the base of support.',
      },
      {
        angle: 'elbow', when: 'top', good: [160, 180], ok: [145, 180],
        cue: 'Arms long through the pull',
        why: 'Early arm bend in the pull reduces bar speed from the legs and hips.',
      },
    ],
    // Shoulder driver: arms hang (~20–60°) → overhead (~170°) once per rep.
    reps: { driver: 'shoulder', start: 'low', enter: 120, exit: 70, target: 165, minRepMs: 1200 },
  },
  {
    id: 'push-jerk',
    name: 'Push Jerk',
    category: 'olympic',
    icon: '🙌',
    mode: 'reps',
    camera: 'side',
    difficulty: 3,
    equipment: ['barbell', 'plates'],
    muscles: ['shoulders', 'triceps', 'quadriceps', 'glutes'],
    summary: 'Vertical dip-drive from the front rack, push under and lock out overhead.',
    setup: [
      'Camera side-on at hip height, 4 m away, bar overhead must stay in frame.',
      'Bar in the front rack, feet hip-width.',
      'Dip straight down, drive up, push under to locked arms.',
      'Stand tall, then return the bar to the rack.',
    ],
    met: 6.0,
    angles: [
      { id: 'shoulder', label: 'Shoulder (arm elevation)', kind: 'joint', joint: 'shoulder' },
      { id: 'elbow', label: 'Elbow', kind: 'joint', joint: 'elbow' },
      { id: 'upperArm', label: 'Arm from vertical', kind: 'segment', segment: 'upperArm', ref: 'vertical' },
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical' },
      { id: 'knee', label: 'Knee', kind: 'joint', joint: 'knee' },
    ],
    checks: [
      {
        angle: 'shoulder', when: 'bottom', good: [165, 180], ok: [150, 180],
        cue: 'Drive the bar fully overhead',
        why: 'Full shoulder flexion places the bar over the trunk for a stable lockout.',
      },
      {
        angle: 'elbow', when: 'bottom', good: [165, 180], ok: [155, 180],
        cue: 'Lock out the elbows',
        why: 'Locked elbows in the receipt are required for a valid jerk and a stable bar.',
        weight: 1.5,
      },
      {
        angle: 'upperArm', when: 'bottom', good: [0, 15], ok: [0, 25],
        cue: 'Bar over your ears',
        why: 'Vertical arms stack the bar over mid-foot.',
      },
      {
        angle: 'knee', when: 'bottom', good: [115, 180], ok: [100, 180],
        cue: 'Receive in a shallow dip',
        why: 'A push-jerk receipt is a partial squat; going deep turns it into a squat jerk.',
        weight: 0.5,
      },
      {
        angle: 'trunk', when: 'top', good: [0, 10], ok: [0, 18],
        cue: 'Dip straight down, torso vertical',
        why: 'A forward-tipping dip drives the bar forward and out of position.',
      },
    ],
    // Front rack shoulder ~70–100° → overhead ~170°.
    reps: { driver: 'shoulder', start: 'low', enter: 135, exit: 115, target: 165, minRepMs: 1000 },
  },
  {
    id: 'split-jerk',
    name: 'Split Jerk',
    category: 'olympic',
    icon: '🔱',
    mode: 'reps',
    camera: 'side',
    difficulty: 3,
    equipment: ['barbell', 'plates'],
    muscles: ['shoulders', 'triceps', 'quadriceps', 'glutes'],
    summary: 'Drive from the rack and split under the bar to a locked-out overhead position.',
    setup: [
      'Camera side-on at hip height, 4 m away; your FRONT leg nearest the camera.',
      'Bar in the front rack, feet hip-width.',
      'Dip, drive, split feet and punch the bar to locked arms.',
      'Recover front foot then back foot, then return the bar.',
    ],
    met: 6.0,
    angles: [
      { id: 'shoulder', label: 'Shoulder (arm elevation)', kind: 'joint', joint: 'shoulder' },
      { id: 'elbow', label: 'Elbow', kind: 'joint', joint: 'elbow' },
      { id: 'upperArm', label: 'Arm from vertical', kind: 'segment', segment: 'upperArm', ref: 'vertical' },
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical' },
    ],
    checks: [
      {
        angle: 'shoulder', when: 'bottom', good: [165, 180], ok: [150, 180],
        cue: 'Punch the bar fully overhead',
        why: 'Full shoulder flexion stacks the bar over the split base.',
      },
      {
        angle: 'elbow', when: 'bottom', good: [165, 180], ok: [155, 180],
        cue: 'Lock the elbows on arrival',
        why: 'Pressing out soft elbows is a no-lift and destabilises the bar.',
        weight: 1.5,
      },
      {
        angle: 'upperArm', when: 'bottom', good: [0, 15], ok: [0, 25],
        cue: 'Bar over your ears',
        why: 'Vertical arms keep the bar over the centre of the split.',
      },
      {
        angle: 'trunk', when: 'bottom', good: [0, 12], ok: [0, 20],
        cue: 'Torso vertical under the bar',
        why: 'An upright trunk keeps the bar over the base between front and back foot.',
      },
      {
        angle: 'trunk', when: 'top', good: [0, 10], ok: [0, 18],
        cue: 'Dip straight down, torso vertical',
        why: 'A vertical dip drives the bar straight up rather than forward.',
      },
    ],
    reps: { driver: 'shoulder', start: 'low', enter: 135, exit: 115, target: 165, minRepMs: 1000 },
  },
  {
    id: 'split-jerk-catch-hold',
    name: 'Split Jerk Catch Hold',
    category: 'olympic',
    icon: '⏱️',
    mode: 'hold',
    camera: 'side',
    difficulty: 3,
    equipment: ['barbell', 'plates'],
    muscles: ['shoulders', 'triceps', 'quadriceps', 'glutes', 'core'],
    summary: 'Hold the split-jerk receiving position with locked arms and a vertical front shin.',
    setup: [
      'Camera side-on at hip height, 4 m away; your FRONT leg nearest the camera.',
      'Jerk the bar and freeze in the split.',
      'Hold: arms locked, front shin vertical, back knee soft.',
    ],
    met: 6.0,
    angles: [
      { id: 'frontKnee', label: 'Front knee', kind: 'joint', joint: 'knee' },
      { id: 'frontShin', label: 'Front shin from vertical', kind: 'segment', segment: 'shin', ref: 'vertical' },
      { id: 'elbow', label: 'Elbow', kind: 'joint', joint: 'elbow' },
      { id: 'upperArm', label: 'Arm from vertical', kind: 'segment', segment: 'upperArm', ref: 'vertical' },
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical' },
    ],
    checks: [
      {
        angle: 'frontKnee', when: 'hold', good: [95, 130], ok: [85, 150],
        cue: 'Bend the front knee more',
        why: 'A front knee around 100–130° gives a low, stable receiving position.',
      },
      {
        angle: 'frontShin', when: 'hold', good: [0, 15], ok: [0, 25],
        cue: 'Front shin vertical',
        why: 'A vertical front shin keeps the knee over the ankle and the base balanced.',
      },
      {
        angle: 'elbow', when: 'hold', good: [165, 180], ok: [155, 180],
        cue: 'Keep elbows locked',
        why: 'Locked elbows transfer the bar load through the skeleton, not the triceps.',
        weight: 1.5,
      },
      {
        angle: 'upperArm', when: 'hold', good: [0, 15], ok: [0, 25],
        cue: 'Bar over your ears',
        why: 'Vertical arms keep the bar over the centre of the split.',
      },
      {
        angle: 'trunk', when: 'hold', good: [0, 12], ok: [0, 20],
        cue: 'Torso vertical, ribs down',
        why: 'An upright trunk keeps the bar stacked over the base.',
      },
    ],
    hold: { targetSec: 3 },
  },
];
