import type { ExerciseDef } from '../types.js';

/**
 * SAI / Khelo India fitness battery, yoga holds and mobility drills.
 * Angle conventions: see types.ts and the catalog spec (2D image plane, degrees).
 */
export const WELLNESS: ExerciseDef[] = [
  // ─────────────────────────── SAI battery ───────────────────────────
  {
    id: 'sai-sit-up',
    name: 'Sit-Ups (SAI Protocol)',
    category: 'sai',
    icon: '🧘',
    mode: 'reps',
    camera: 'side',
    difficulty: 1,
    equipment: ['mat'],
    muscles: ['rectus abdominis', 'hip flexors', 'obliques'],
    summary: 'Maximum bent-knee sit-ups in 60 seconds, per the SAI KIRTI talent battery.',
    setup: [
      'Place the camera at hip height, side-on, 2–3 m away.',
      'Lie on your back, knees bent about 90°, feet flat and held.',
      'Cross arms on chest; curl up until elbows touch thighs.',
    ],
    met: 7.5, // Compendium 2024 02020 (sit-ups, vigorous)
    angles: [
      { id: 'hip', label: 'Hip angle', kind: 'joint', joint: 'hip', side: 'auto' },
      { id: 'knee', label: 'Knee angle', kind: 'joint', joint: 'knee', side: 'auto' },
    ],
    reps: { driver: 'hip', start: 'high', enter: 105, exit: 122, target: 65, minRepMs: 700 },
    checks: [
      {
        angle: 'hip',
        when: 'bottom',
        good: [30, 65],
        ok: [20, 80],
        cue: 'Sit all the way up',
        why: 'The SAI protocol only counts reps where the elbows reach the thighs.',
      },
      {
        angle: 'hip',
        when: 'top',
        good: [128, 180],
        ok: [122, 180],
        cue: 'Lower shoulders back to the mat',
        why: 'Each rep must return the shoulder blades to the floor to be valid.',
      },
      {
        angle: 'knee',
        when: 'active',
        good: [70, 100],
        ok: [55, 115],
        cue: 'Keep knees bent near 90°',
        why: 'Straight-leg sit-ups shift load to the hip flexors and raise lumbar compression.',
      },
    ],
  },
  {
    id: 'sai-partial-curl-up',
    name: 'Partial Curl-Ups (SAI Protocol)',
    category: 'sai',
    icon: '🌀',
    mode: 'reps',
    camera: 'side',
    difficulty: 1,
    equipment: ['mat', 'measuring strip'],
    muscles: ['rectus abdominis', 'obliques'],
    summary: 'Maximum correct partial curl-ups in 30 s, lifting only the shoulder blades.',
    setup: [
      'Place the camera at floor level, side-on, 2–3 m away.',
      'Lie on your back, knees bent about 90°, feet flat.',
      'Arms straight by your sides, fingertips on the strip.',
      'Curl up slowly, sliding fingers forward, then lower.',
    ],
    met: 2.8, // Compendium 2024 02024 (light calisthenics)
    angles: [
      { id: 'trunk', label: 'Trunk inclination', kind: 'segment', segment: 'trunk', ref: 'vertical', side: 'auto' },
      { id: 'knee', label: 'Knee angle', kind: 'joint', joint: 'knee', side: 'auto' },
      { id: 'elbow', label: 'Elbow angle', kind: 'joint', joint: 'elbow', side: 'auto' },
    ],
    reps: { driver: 'trunk', start: 'high', enter: 70, exit: 85, target: 68, minRepMs: 1000 },
    checks: [
      {
        angle: 'trunk',
        when: 'bottom',
        good: [50, 68],
        ok: [40, 75],
        cue: 'Lift shoulder blades clear of the mat',
        why: 'A 20–30° trunk lift isolates the abdominals without hip-flexor dominance.',
      },
      {
        angle: 'trunk',
        when: 'top',
        good: [87, 100],
        ok: [82, 105],
        cue: 'Lower head fully back down',
        why: 'The protocol requires the head to return to the mat between reps.',
      },
      {
        angle: 'knee',
        when: 'active',
        good: [80, 100],
        ok: [70, 115],
        cue: 'Keep knees bent near 90°',
        why: 'Khelo India specifies knees flexed at about 90° so scores stay comparable across testers.',
      },
      {
        angle: 'elbow',
        when: 'active',
        good: [160, 180],
        ok: [145, 180],
        cue: 'Keep arms straight, palms down',
        why: 'Bending the elbows lets the hands slide without a real trunk curl.',
      },
    ],
  },
  {
    id: 'sai-sit-and-reach',
    name: 'Sit and Reach (SAI Protocol)',
    category: 'sai',
    icon: '📏',
    mode: 'hold',
    camera: 'side',
    difficulty: 1,
    equipment: ['sit-and-reach box'],
    muscles: ['hamstrings', 'erector spinae', 'gluteus maximus'],
    summary: 'Seated forward reach with straight legs, measuring hamstring and lower-back flexibility. Official score is in cm; Fitzen scores the trunk–hip angle instead.',
    setup: [
      'Place the camera at hip height, side-on, 2 m away.',
      'Sit with legs straight, soles flat against the box.',
      'Stack hands and reach forward slowly as far as possible.',
      'Hold the furthest reach steady.',
    ],
    met: 2.3,
    angles: [
      { id: 'hip', label: 'Hip angle (trunk to thigh)', kind: 'joint', joint: 'hip', side: 'auto' },
      { id: 'knee', label: 'Knee angle', kind: 'joint', joint: 'knee', side: 'auto' },
      { id: 'elbow', label: 'Elbow angle', kind: 'joint', joint: 'elbow', side: 'auto' },
    ],
    hold: { targetSec: 2 },
    checks: [
      {
        angle: 'hip',
        when: 'hold',
        good: [0, 60],
        ok: [0, 80],
        cue: 'Fold forward from the hips',
        why: 'A smaller trunk-to-thigh angle reflects greater hamstring and hip flexibility.',
        weight: 2,
      },
      {
        angle: 'knee',
        when: 'hold',
        good: [165, 180],
        ok: [155, 180],
        cue: 'Press knees flat, legs straight',
        why: 'Bending the knees slackens the hamstrings and invalidates the score.',
      },
      {
        angle: 'elbow',
        when: 'hold',
        good: [160, 180],
        ok: [145, 180],
        cue: 'Reach with arms fully straight',
        why: 'Bent elbows shorten the reach and understate flexibility.',
      },
    ],
  },
  {
    id: 'sai-flamingo-balance',
    name: 'Flamingo Balance (SAI Protocol)',
    category: 'sai',
    icon: '🦩',
    mode: 'hold',
    camera: 'front',
    difficulty: 2,
    equipment: [],
    muscles: ['ankle stabilisers', 'gluteus medius', 'core'],
    summary: 'Single-leg stance holding the other foot behind, measuring static balance. Official score is falls in 60 s (Fit India Fitness Protocol 5–18 y); Fitzen reports time held.',
    setup: [
      'Place the camera at chest height, facing you, 3 m away.',
      'Stand on your preferred leg.',
      'Bend the other knee and hold that foot behind you.',
      'Stay tall and still as long as possible.',
    ],
    met: 2.3,
    angles: [
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical', side: 'both' },
      { id: 'shoulders', label: 'Shoulder tilt', kind: 'segment', segment: 'shoulders', ref: 'horizontal' },
      { id: 'hips', label: 'Pelvic tilt', kind: 'segment', segment: 'hips', ref: 'horizontal' },
    ],
    hold: { targetSec: 60 },
    checks: [
      {
        angle: 'trunk',
        when: 'hold',
        good: [0, 10],
        ok: [0, 16],
        cue: 'Stand tall, trunk upright',
        why: 'Trunk lean is the main compensatory strategy for poor single-leg balance.',
      },
      {
        angle: 'shoulders',
        when: 'hold',
        good: [0, 5],
        ok: [0, 10],
        cue: 'Level your shoulders',
        why: 'Shoulder tilt reveals lateral sway of the centre of mass.',
      },
      {
        angle: 'hips',
        when: 'hold',
        good: [0, 6],
        ok: [0, 12],
        cue: 'Keep hips level',
        why: 'Pelvic drop signals weak hip abductors on the stance side.',
      },
    ],
  },
  {
    id: 'sai-push-up',
    name: 'Push-Ups (SAI Protocol)',
    category: 'sai',
    icon: '💪',
    mode: 'reps',
    camera: 'side',
    difficulty: 2,
    equipment: [],
    muscles: ['pectoralis major', 'triceps', 'anterior deltoid', 'core'],
    summary: 'Maximum full push-ups with a rigid body line, per the SAI Khelo India battery. Girls\' protocol is knee-down: use Knee Push-Up.',
    setup: [
      'Place the camera at floor level, side-on, 2–3 m away.',
      'Hands under shoulders, body straight from head to heels.',
      'Lower until elbows reach 90°, then press to lockout.',
    ],
    met: 7.5, // Compendium 2024 02020
    angles: [
      { id: 'elbow', label: 'Elbow angle', kind: 'joint', joint: 'elbow', side: 'auto' },
      { id: 'bodyLine', label: 'Body line', kind: 'joint', joint: 'bodyLine', side: 'auto' },
      { id: 'hip', label: 'Hip angle', kind: 'joint', joint: 'hip', side: 'auto' },
    ],
    reps: { driver: 'elbow', start: 'high', enter: 145, exit: 160, target: 95 },
    checks: [
      {
        angle: 'elbow',
        when: 'bottom',
        good: [60, 95],
        ok: [50, 110],
        cue: 'Lower until elbows reach 90°',
        why: 'The SAI standard counts only reps with upper arms parallel to the floor.',
      },
      {
        angle: 'elbow',
        when: 'top',
        good: [165, 180],
        ok: [160, 180],
        cue: 'Lock arms out at the top',
        why: 'Full extension defines a complete repetition in standardised tests.',
      },
      {
        angle: 'bodyLine',
        when: 'active',
        good: [165, 180],
        ok: [155, 180],
        cue: 'Keep body straight, brace core',
        why: 'Hip sag or pike reduces load and is the most common invalid rep.',
        weight: 0.5,
      },
      {
        angle: 'hip',
        when: 'active',
        good: [160, 180],
        ok: [150, 180],
        cue: 'Squeeze glutes, hips in line',
        why: 'Hip flexion shortens the lever and signals core fatigue.',
        weight: 0.5,
      },
    ],
  },
  {
    id: 'sai-medicine-ball-throw',
    name: 'Seated Medicine Ball Chest Throw (SAI)',
    category: 'sai',
    icon: '🏐',
    mode: 'event',
    camera: 'side',
    difficulty: 2,
    equipment: ['medicine ball (1 kg / 2 kg)', 'wall', 'tape measure'],
    muscles: ['pectoralis major', 'triceps', 'anterior deltoid'],
    summary: 'Seated two-hand chest pass with back to the wall, measuring upper-body power. Measure distance with a tape; Fitzen scores release form and angle.',
    setup: [
      'Place the camera at chest height, side-on, 3 m away.',
      'Sit with back against a wall, legs straight.',
      'Hold the ball at chest, elbows out.',
      'Push it forward and up as far as possible.',
    ],
    met: 4.0,
    angles: [
      { id: 'elbow', label: 'Elbow angle', kind: 'joint', joint: 'elbow', side: 'auto' },
      { id: 'shoulder', label: 'Arm elevation', kind: 'joint', joint: 'shoulder', side: 'auto' },
      { id: 'trunk', label: 'Trunk inclination', kind: 'segment', segment: 'trunk', ref: 'vertical', side: 'auto' },
      { id: 'knee', label: 'Knee angle', kind: 'joint', joint: 'knee', side: 'auto' },
    ],
    event: { trigger: 'wristPeak', releaseAngle: { good: [35, 45], ok: [25, 55] } },
    checks: [
      {
        angle: 'elbow',
        when: 'release',
        good: [155, 180],
        ok: [140, 180],
        cue: 'Punch arms fully straight',
        why: 'Complete elbow extension at release maximises ball velocity.',
        weight: 2,
      },
      {
        angle: 'shoulder',
        when: 'release',
        good: [115, 145],
        ok: [95, 160],
        cue: 'Push forward and slightly up',
        why: 'Release around 35–45° above horizontal optimises horizontal distance for a seated throw.',
      },
      {
        angle: 'trunk',
        when: 'release',
        good: [0, 15],
        ok: [0, 25],
        cue: 'Keep back against the wall',
        why: 'The protocol isolates the arms; trunk lunging inflates the score.',
      },
      {
        angle: 'knee',
        when: 'any',
        good: [160, 180],
        ok: [145, 180],
        cue: 'Keep legs straight on the floor',
        why: 'A fixed seated base keeps results standardised between athletes.',
      },
    ],
  },
  {
    id: 'sai-vertical-jump',
    name: 'Vertical Jump (SAI Protocol)',
    category: 'sai',
    icon: '⬆️',
    mode: 'event',
    camera: 'side',
    difficulty: 2,
    equipment: ['wall with measuring scale'],
    muscles: ['quadriceps', 'gluteus maximus', 'calves'],
    summary: 'Countermovement jump-and-reach from standing, measuring lower-body explosive power. Fitzen gives flight-time height, not reach height, so it is not comparable with SAI norm tables.',
    setup: [
      'Place the camera at hip height, side-on, 3 m away.',
      'Stand tall with feet hip-width apart.',
      'Dip, swing arms, and jump straight up reaching high.',
      'Land softly on both feet.',
    ],
    met: 6.0,
    angles: [
      { id: 'knee', label: 'Knee angle', kind: 'joint', joint: 'knee', side: 'auto' },
      { id: 'hip', label: 'Hip angle', kind: 'joint', joint: 'hip', side: 'auto' },
      { id: 'trunk', label: 'Trunk inclination', kind: 'segment', segment: 'trunk', ref: 'vertical', side: 'auto' },
      { id: 'shoulder', label: 'Arm elevation', kind: 'joint', joint: 'shoulder', side: 'auto' },
      { id: 'ankle', label: 'Ankle angle', kind: 'joint', joint: 'ankle', side: 'auto' },
    ],
    event: { trigger: 'jump' },
    checks: [
      {
        angle: 'knee',
        when: 'bottom',
        good: [80, 110],
        ok: [65, 130],
        cue: 'Dip to a quarter-to-half squat',
        why: 'A countermovement to roughly 70–100° of knee flexion maximises jump height via stretch-shortening.',
      },
      {
        angle: 'trunk',
        when: 'bottom',
        good: [20, 50],
        ok: [10, 60],
        cue: 'Hinge slightly, chest up',
        why: 'Moderate trunk flexion loads the hips without collapsing the jump direction.',
      },
      {
        angle: 'knee',
        when: 'release',
        good: [165, 180],
        ok: [155, 180],
        cue: 'Drive through to straight legs',
        why: 'Full knee extension at take-off completes the propulsive impulse.',
      },
      {
        angle: 'hip',
        when: 'release',
        good: [165, 180],
        ok: [150, 180],
        cue: 'Extend hips fully at take-off',
        why: 'Hip and knee extension together provide most of the jump work (Hubley & Wells 1983).',
      },
      {
        angle: 'shoulder',
        when: 'release',
        good: [140, 180],
        ok: [110, 180],
        cue: 'Swing arms up hard',
        why: 'An arm swing increases countermovement jump height by around 10%.',
      },
      {
        angle: 'ankle',
        when: 'release',
        good: [115, 160],
        ok: [105, 170],
        cue: 'Push off through the toes',
        why: 'Ankle plantarflexion is the final link of the triple extension.',
      },
    ],
  },
  {
    id: 'sai-broad-jump',
    name: 'Standing Broad Jump (SAI Protocol)',
    category: 'sai',
    icon: '🦘',
    mode: 'event',
    camera: 'side',
    difficulty: 2,
    equipment: ['tape measure', 'non-slip surface'],
    muscles: ['quadriceps', 'gluteus maximus', 'hamstrings', 'calves'],
    summary: 'Two-foot standing long jump for distance, measuring horizontal explosive power. Measure distance with a tape; Fitzen scores take-off form and angle.',
    setup: [
      'Place the camera at hip height, side-on, 4 m away.',
      'Stand behind the line, feet shoulder-width apart.',
      'Swing arms back, dip, then jump forward as far as possible.',
      'Land on both feet without falling back.',
    ],
    met: 6.0,
    angles: [
      { id: 'knee', label: 'Knee angle', kind: 'joint', joint: 'knee', side: 'auto' },
      { id: 'hip', label: 'Hip angle', kind: 'joint', joint: 'hip', side: 'auto' },
      { id: 'trunk', label: 'Trunk inclination', kind: 'segment', segment: 'trunk', ref: 'vertical', side: 'auto' },
      { id: 'shoulder', label: 'Arm elevation', kind: 'joint', joint: 'shoulder', side: 'auto' },
    ],
    event: { trigger: 'jump', releaseAngle: { good: [20, 35], ok: [15, 42] } },
    checks: [
      {
        angle: 'knee',
        when: 'bottom',
        good: [70, 110],
        ok: [55, 130],
        cue: 'Load deeper before take-off',
        why: 'A deeper countermovement lengthens the propulsive phase for more distance.',
      },
      {
        angle: 'trunk',
        when: 'bottom',
        good: [35, 70],
        ok: [20, 80],
        cue: 'Lean forward, arms swung back',
        why: 'Forward trunk lean at the bottom aims the take-off impulse horizontally.',
      },
      {
        angle: 'knee',
        when: 'release',
        good: [160, 180],
        ok: [145, 180],
        cue: 'Extend legs fully off the line',
        why: 'Incomplete knee extension at take-off wastes propulsive force.',
      },
      {
        angle: 'hip',
        when: 'release',
        good: [160, 180],
        ok: [145, 180],
        cue: 'Drive hips forward through take-off',
        why: 'Hip extension is the dominant contributor to standing long jump distance.',
      },
      {
        angle: 'shoulder',
        when: 'release',
        good: [120, 180],
        ok: [90, 180],
        cue: 'Throw arms forward and up',
        why: 'Arm swing improves standing long jump distance by roughly 20%.',
      },
    ],
  },

  // ───────────────────────────── Yoga ─────────────────────────────
  {
    id: 'tree-pose',
    name: 'Tree Pose (Vrikshasana)',
    category: 'yoga',
    icon: '🌳',
    mode: 'hold',
    camera: 'front',
    difficulty: 1,
    equipment: ['mat'],
    muscles: ['gluteus medius', 'ankle stabilisers', 'core'],
    summary: 'Single-leg balance with the sole placed on the inner standing leg.',
    setup: [
      'Place the camera at chest height, facing you, 3 m away.',
      'Stand on one leg (do both sides).',
      'Place the other sole on the inner thigh or calf, never the knee.',
      'Palms together at chest or overhead.',
    ],
    met: 2.3, // Compendium 2024 02150 Yoga, Hatha
    angles: [
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical', side: 'both' },
      { id: 'hips', label: 'Pelvic tilt', kind: 'segment', segment: 'hips', ref: 'horizontal' },
      { id: 'shoulders', label: 'Shoulder tilt', kind: 'segment', segment: 'shoulders', ref: 'horizontal' },
    ],
    hold: { targetSec: 30 },
    checks: [
      {
        angle: 'trunk',
        when: 'hold',
        good: [0, 9],
        ok: [0, 14],
        cue: 'Grow tall through the crown',
        why: 'Trunk lean shifts the centre of mass outside the base of support (AYUSH Common Yoga Protocol: hold 10–30 s).',
      },
      {
        angle: 'hips',
        when: 'hold',
        good: [0, 5],
        ok: [0, 10],
        cue: 'Keep both hips level',
        why: 'Hip hiking on the lifted side is a common compensation in tree pose.',
      },
      {
        angle: 'shoulders',
        when: 'hold',
        good: [0, 5],
        ok: [0, 10],
        cue: 'Relax and level the shoulders',
        why: 'Shoulder tilt indicates lateral sway and poor postural control.',
      },
    ],
  },
  {
    id: 'warrior-ii',
    name: 'Warrior II (Virabhadrasana II)',
    category: 'yoga',
    icon: '⚔️',
    mode: 'hold',
    camera: 'front',
    difficulty: 2,
    equipment: ['mat'],
    muscles: ['quadriceps', 'gluteus medius', 'adductors', 'deltoids'],
    summary: 'Wide lunge with front knee bent and arms extended horizontally.',
    setup: [
      'Place the camera at hip height, facing you, 3–4 m away.',
      'Step feet wide; bend the left knee over the ankle.',
      'Keep the right leg straight.',
      'Raise arms to shoulder height, reaching sideways.',
    ],
    met: 2.3, // Compendium 2024 02150 Yoga, Hatha
    angles: [
      // Bent knee = front leg, straight knee = back leg, whichever side leads.
      { id: 'frontKnee', label: 'Front knee', kind: 'joint', joint: 'knee', side: 'flexed' },
      { id: 'backKnee', label: 'Back knee', kind: 'joint', joint: 'knee', side: 'extended' },
      { id: 'shoulder', label: 'Arm elevation', kind: 'joint', joint: 'shoulder', side: 'both' },
      { id: 'elbow', label: 'Elbow angle', kind: 'joint', joint: 'elbow', side: 'both' },
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical', side: 'both' },
      { id: 'stance', label: 'Stance width', kind: 'spread', what: 'feet' },
    ],
    hold: { targetSec: 30 },
    checks: [
      {
        angle: 'frontKnee',
        when: 'hold',
        good: [85, 120],
        ok: [75, 140],
        cue: 'Bend front knee toward 90°',
        why: 'Manuals cue 90°; experienced practitioners averaged 68 ± 20° flexion (~112° here) in motion capture (Whissell et al. 2021).',
        weight: 2,
      },
      {
        angle: 'backKnee',
        when: 'hold',
        good: [165, 180],
        ok: [155, 180],
        cue: 'Straighten the back leg',
        why: 'An extended back leg anchors the stance and stretches the adductors.',
      },
      {
        angle: 'shoulder',
        when: 'hold',
        good: [80, 100],
        ok: [70, 110],
        cue: 'Arms level at shoulder height',
        why: 'Horizontal arms train deltoid endurance and cue an open chest.',
      },
      {
        angle: 'elbow',
        when: 'hold',
        good: [160, 180],
        ok: [150, 180],
        cue: 'Reach through straight arms',
        why: 'Straight arms maintain the long lever the pose relies on.',
      },
      {
        angle: 'trunk',
        when: 'hold',
        good: [0, 8],
        ok: [0, 15],
        cue: 'Stack torso over the hips',
        why: 'Leaning toward the front leg shifts load off the working hip.',
      },
      {
        angle: 'stance',
        when: 'hold',
        good: [2.2, 3.5],
        ok: [1.8, 4.2],
        cue: 'Widen or narrow your stance',
        why: 'About one leg-length between feet lets the front knee reach 90° over the ankle.',
      },
    ],
  },
  {
    id: 'warrior-i',
    name: 'Warrior I (Virabhadrasana I)',
    category: 'yoga',
    icon: '🗡️',
    mode: 'hold',
    camera: 'side',
    difficulty: 2,
    equipment: ['mat'],
    muscles: ['quadriceps', 'gluteus maximus', 'hip flexors', 'deltoids'],
    summary: 'Front-facing lunge with arms overhead and an upright torso.',
    setup: [
      'Place the camera at hip height, side-on, 3 m away.',
      'Step forward with the leg nearer the camera; bend that knee.',
      'Keep the back leg straight behind you (repeat facing the other way).',
      'Raise both arms overhead.',
    ],
    met: 2.3, // Compendium 2024 02150 Yoga, Hatha
    angles: [
      // Bent knee = front leg, whichever side leads. ponytail: no back-knee check: the demo puppet can't draw split legs.
      { id: 'frontKnee', label: 'Front knee', kind: 'joint', joint: 'knee', side: 'flexed' },
      { id: 'trunk', label: 'Trunk inclination', kind: 'segment', segment: 'trunk', ref: 'vertical', side: 'auto' },
      { id: 'shoulder', label: 'Arm elevation', kind: 'joint', joint: 'shoulder', side: 'auto' },
      { id: 'elbow', label: 'Elbow angle', kind: 'joint', joint: 'elbow', side: 'auto' },
    ],
    hold: { targetSec: 30 },
    checks: [
      {
        angle: 'frontKnee',
        when: 'hold',
        good: [85, 110],
        ok: [75, 130],
        cue: 'Sink front knee toward 90°',
        why: 'A deep front knee develops quadriceps and gluteal strength.',
        weight: 2,
      },
      {
        angle: 'trunk',
        when: 'hold',
        good: [0, 10],
        ok: [0, 20],
        cue: 'Lift chest, torso upright',
        why: 'Forward lean removes the hip-flexor stretch the pose targets.',
      },
      {
        angle: 'shoulder',
        when: 'hold',
        good: [160, 180],
        ok: [145, 180],
        cue: 'Reach arms fully overhead',
        why: 'Full shoulder flexion trains overhead mobility and thoracic extension.',
      },
      {
        angle: 'elbow',
        when: 'hold',
        good: [165, 180],
        ok: [150, 180],
        cue: 'Straighten your arms',
        why: 'Bent elbows usually mask limited shoulder flexion.',
      },
    ],
  },
  {
    id: 'chair-pose',
    name: 'Chair Pose (Utkatasana)',
    category: 'yoga',
    icon: '🪑',
    mode: 'hold',
    camera: 'side',
    difficulty: 2,
    equipment: ['mat'],
    muscles: ['quadriceps', 'gluteus maximus', 'erector spinae', 'deltoids'],
    summary: 'Seated-back squat hold with arms overhead, building leg endurance.',
    setup: [
      'Place the camera at hip height, side-on, 3 m away.',
      'Stand with feet together or hip-width.',
      'Sit hips back as if onto a chair.',
      'Raise arms overhead alongside the ears.',
    ],
    met: 2.8, // Compendium 2024 02024 light calisthenics (isometric holds like plank); 4.0 is flowing Power yoga
    angles: [
      { id: 'knee', label: 'Knee angle', kind: 'joint', joint: 'knee', side: 'auto' },
      { id: 'hip', label: 'Hip angle', kind: 'joint', joint: 'hip', side: 'auto' },
      { id: 'trunk', label: 'Trunk inclination', kind: 'segment', segment: 'trunk', ref: 'vertical', side: 'auto' },
      { id: 'shin', label: 'Shin inclination', kind: 'segment', segment: 'shin', ref: 'vertical', side: 'auto' },
      { id: 'shoulder', label: 'Arm elevation', kind: 'joint', joint: 'shoulder', side: 'auto' },
    ],
    hold: { targetSec: 30 },
    checks: [
      {
        angle: 'knee',
        when: 'hold',
        good: [90, 120],
        ok: [75, 140],
        cue: 'Sit lower, thighs toward parallel',
        why: 'Knee flexion near 90–120° gives the quadriceps a meaningful isometric load.',
        weight: 2,
      },
      {
        angle: 'hip',
        when: 'hold',
        good: [70, 110],
        ok: [60, 130],
        cue: 'Send hips back',
        why: 'Hip flexion shares the load with the glutes and protects the knees.',
      },
      {
        angle: 'trunk',
        when: 'hold',
        good: [20, 45],
        ok: [10, 55],
        cue: 'Lift chest, don’t fold forward',
        why: 'Excess trunk lean turns the pose into a hinge and loads the lower back.',
      },
      {
        angle: 'shin',
        when: 'hold',
        good: [15, 40],
        ok: [5, 50],
        cue: 'Keep weight in your heels',
        why: 'Excess forward shin angle shifts weight to the toes and raises knee stress.',
      },
      {
        angle: 'shoulder',
        when: 'hold',
        good: [150, 180],
        ok: [130, 180],
        cue: 'Reach arms up by your ears',
        why: 'Overhead arms challenge thoracic extension and shoulder endurance.',
      },
    ],
  },
  {
    id: 'downward-dog',
    name: 'Downward-Facing Dog (Adho Mukha Svanasana)',
    category: 'yoga',
    icon: '🐕',
    mode: 'hold',
    camera: 'side',
    difficulty: 1,
    equipment: ['mat'],
    muscles: ['hamstrings', 'calves', 'deltoids', 'latissimus dorsi'],
    summary: 'Inverted V with hips high, legs and arms long, stretching the posterior chain.',
    setup: [
      'Place the camera at floor level, side-on, 3 m away.',
      'Start on hands and knees, hands shoulder-width.',
      'Lift hips up and back into an inverted V.',
      'Press heels toward the floor.',
    ],
    met: 2.3, // Compendium 2024 02150 Yoga, Hatha
    angles: [
      { id: 'hip', label: 'Hip angle', kind: 'joint', joint: 'hip', side: 'auto' },
      { id: 'knee', label: 'Knee angle', kind: 'joint', joint: 'knee', side: 'auto' },
      { id: 'elbow', label: 'Elbow angle', kind: 'joint', joint: 'elbow', side: 'auto' },
      { id: 'shoulder', label: 'Shoulder angle', kind: 'joint', joint: 'shoulder', side: 'auto' },
    ],
    hold: { targetSec: 30 },
    checks: [
      {
        angle: 'hip',
        when: 'hold',
        good: [60, 95],
        ok: [50, 110],
        cue: 'Lift hips high and back',
        why: 'Motion capture of the inverted-V pose shows ~67° hip flexion plus spinal flexion with near-straight knees (Mullerpatan et al. 2019).',
        weight: 2,
      },
      {
        angle: 'knee',
        when: 'hold',
        good: [165, 180],
        ok: [150, 180],
        cue: 'Straighten legs if you can',
        why: 'Straight knees lengthen the hamstrings and calves.',
      },
      {
        angle: 'elbow',
        when: 'hold',
        good: [165, 180],
        ok: [150, 180],
        cue: 'Press floor away, arms straight',
        why: 'Locked-long arms load the shoulders safely instead of collapsing the chest.',
      },
      {
        angle: 'shoulder',
        when: 'hold',
        good: [155, 180],
        ok: [140, 180],
        cue: 'Arms in line with your spine',
        why: 'Full shoulder flexion keeps the spine long and trains overhead mobility.',
      },
    ],
  },
  {
    id: 'cobra-pose',
    name: 'Cobra Pose (Bhujangasana)',
    category: 'yoga',
    icon: '🐍',
    mode: 'hold',
    camera: 'side',
    difficulty: 1,
    equipment: ['mat'],
    muscles: ['erector spinae', 'gluteus maximus', 'abdominals (stretch)'],
    summary: 'Prone back-bend lifting the chest with legs extended on the floor.',
    setup: [
      'Place the camera at floor level, side-on, 3 m away.',
      'Lie face down, legs straight, tops of feet down.',
      'Hands under shoulders, elbows close to ribs.',
      'Press up to lift the chest.',
    ],
    met: 2.3, // Compendium 2024 02150 Yoga, Hatha
    angles: [
      { id: 'trunk', label: 'Trunk inclination', kind: 'segment', segment: 'trunk', ref: 'vertical', side: 'auto' },
      { id: 'knee', label: 'Knee angle', kind: 'joint', joint: 'knee', side: 'auto' },
      { id: 'upperArm', label: 'Upper-arm inclination', kind: 'segment', segment: 'upperArm', ref: 'vertical', side: 'auto' },
    ],
    hold: { targetSec: 20 },
    checks: [
      {
        angle: 'trunk',
        when: 'hold',
        good: [40, 70],
        ok: [30, 80],
        cue: 'Lift chest to navel height',
        why: 'AYUSH Common Yoga Protocol: lift chin and chest up to the navel region, legs firm so the lumbar spine is not strained.',
        weight: 2,
      },
      {
        angle: 'knee',
        when: 'hold',
        good: [165, 180],
        ok: [150, 180],
        cue: 'Keep legs long on the mat',
        why: 'Bent knees tip the pelvis and move the bend into the lumbar spine.',
      },
      {
        angle: 'upperArm',
        when: 'hold',
        good: [135, 180],
        ok: [120, 180],
        cue: 'Elbows in, shoulders away from ears',
        why: 'AYUSH protocol keeps palms beside the chest with elbows bent, so the upper arm hangs near vertical (~180°) or tilts back a little.',
      },
    ],
  },
  {
    id: 'triangle-pose',
    name: 'Triangle Pose (Trikonasana)',
    category: 'yoga',
    icon: '🔺',
    mode: 'hold',
    camera: 'front',
    difficulty: 2,
    equipment: ['mat'],
    muscles: ['obliques', 'hamstrings', 'adductors', 'quadratus lumborum'],
    summary: 'Wide straight-legged stance with a lateral trunk bend and arms in a vertical line.',
    setup: [
      'Place the camera at hip height, facing you, 3–4 m away.',
      'Step feet wide, legs straight.',
      'Reach sideways, lowering one hand to shin or floor.',
      'Extend the other arm straight up.',
    ],
    met: 2.3, // Compendium 2024 02150 Yoga, Hatha
    angles: [
      { id: 'knee', label: 'Knee angle', kind: 'joint', joint: 'knee', side: 'both' },
      { id: 'trunk', label: 'Trunk side-bend', kind: 'segment', segment: 'trunk', ref: 'vertical', side: 'auto' },
      { id: 'elbow', label: 'Elbow angle', kind: 'joint', joint: 'elbow', side: 'both' },
      { id: 'upperArm', label: 'Arm stack (upper arm vs horizontal)', kind: 'segment', segment: 'upperArm', ref: 'horizontal', side: 'both' },
    ],
    hold: { targetSec: 30 },
    checks: [
      {
        angle: 'knee',
        when: 'hold',
        good: [165, 180],
        ok: [155, 180],
        cue: 'Keep both legs straight',
        why: 'Straight legs deliver the hamstring and adductor stretch of the pose.',
      },
      {
        angle: 'trunk',
        when: 'hold',
        good: [40, 80],
        ok: [25, 90],
        cue: 'Bend sideways, hand toward shin',
        why: 'AYUSH protocol: bend sideways toward the foot, or reach the knee instead; do not overdo the lateral stretch.',
        weight: 2,
      },
      {
        angle: 'elbow',
        when: 'hold',
        good: [165, 180],
        ok: [150, 180],
        cue: 'Straighten both arms',
        why: 'Straight arms keep the shoulder line long and aligned.',
      },
      {
        angle: 'upperArm',
        when: 'hold',
        good: [75, 90],
        ok: [60, 90],
        cue: 'Stack top arm over bottom arm',
        why: 'Both arms vertical in one line open the chest toward the camera.',
      },
    ],
  },
  {
    id: 'boat-pose',
    name: 'Boat Pose (Navasana)',
    category: 'yoga',
    icon: '⛵',
    mode: 'hold',
    camera: 'side',
    difficulty: 3,
    equipment: ['mat'],
    muscles: ['rectus abdominis', 'hip flexors', 'obliques'],
    summary: 'Seated V-balance on the sit bones with legs raised and arms reaching forward.',
    setup: [
      'Place the camera at floor level, side-on, 3 m away.',
      'Sit, lean back slightly, lift feet off the floor.',
      'Straighten legs toward a V shape.',
      'Reach arms forward parallel to the floor.',
    ],
    met: 2.8, // Compendium 2024 02024 light calisthenics (isometric holds like plank)
    angles: [
      { id: 'hip', label: 'Hip angle', kind: 'joint', joint: 'hip', side: 'auto' },
      { id: 'trunk', label: 'Trunk inclination', kind: 'segment', segment: 'trunk', ref: 'vertical', side: 'auto' },
      { id: 'knee', label: 'Knee angle', kind: 'joint', joint: 'knee', side: 'auto' },
      { id: 'thigh', label: 'Thigh inclination', kind: 'segment', segment: 'thigh', ref: 'vertical', side: 'auto' },
      { id: 'shoulder', label: 'Arm-to-trunk angle', kind: 'joint', joint: 'shoulder', side: 'auto' },
    ],
    hold: { targetSec: 20 },
    checks: [
      {
        angle: 'hip',
        when: 'hold',
        good: [55, 90],
        ok: [45, 110],
        cue: 'Draw legs and chest into a V',
        why: 'A closed hip angle keeps the abdominals and hip flexors under isometric load.',
        weight: 2,
      },
      {
        angle: 'trunk',
        when: 'hold',
        good: [20, 45],
        ok: [10, 60],
        cue: 'Recline about 30°, chest lifted',
        why: 'Excess recline turns the pose into a lumbar-loading lever.',
      },
      {
        angle: 'knee',
        when: 'hold',
        good: [155, 180],
        ok: [90, 180],
        cue: 'Extend legs when you can',
        why: 'Straight legs lengthen the lever and increase core demand.',
      },
      {
        angle: 'thigh',
        when: 'hold',
        good: [25, 60],
        ok: [15, 75],
        cue: 'Hold thighs about 45° up',
        why: 'Thighs raised about 45° hold the hip flexors in their strong range.',
      },
      {
        angle: 'shoulder',
        when: 'hold',
        good: [45, 75],
        ok: [35, 90],
        cue: 'Reach arms parallel to the floor',
        why: 'Horizontal arms keep the upper back engaged and the chest open.',
      },
    ],
  },
  {
    id: 'bridge-pose',
    name: 'Bridge Pose (Setu Bandha Sarvangasana)',
    category: 'yoga',
    icon: '🌉',
    mode: 'hold',
    camera: 'side',
    difficulty: 1,
    equipment: ['mat'],
    muscles: ['gluteus maximus', 'hamstrings', 'erector spinae'],
    summary: 'Supine hip lift to a straight shoulder-to-knee line with shins vertical.',
    setup: [
      'Place the camera at floor level, side-on, 3 m away.',
      'Lie on your back, knees bent, feet hip-width.',
      'Press through heels and lift the hips.',
      'Hold a straight line from shoulders to knees.',
    ],
    met: 2.3, // Compendium 2024 02150 Yoga, Hatha
    angles: [
      { id: 'hip', label: 'Hip angle', kind: 'joint', joint: 'hip', side: 'auto' },
      { id: 'knee', label: 'Knee angle', kind: 'joint', joint: 'knee', side: 'auto' },
      { id: 'shin', label: 'Shin inclination', kind: 'segment', segment: 'shin', ref: 'vertical', side: 'auto' },
    ],
    hold: { targetSec: 30 },
    checks: [
      {
        angle: 'hip',
        when: 'hold',
        good: [165, 180],
        ok: [150, 180],
        cue: 'Squeeze glutes, lift hips higher',
        why: 'Full hip extension maximises gluteus maximus activation.',
        weight: 2,
      },
      {
        angle: 'knee',
        when: 'hold',
        good: [45, 80],
        ok: [35, 95],
        cue: 'Walk heels in toward your hips',
        why: 'Feet under the knees reads ~65°; the AYUSH protocol brings heels near the buttocks, closing it further.',
      },
      {
        angle: 'shin',
        when: 'hold',
        good: [0, 25],
        ok: [0, 35],
        cue: 'Heels near hips, under the knees',
        why: 'Near-vertical shins keep load on the glutes; feet far away shift it to the hamstrings.',
      },
    ],
  },
  {
    id: 'mountain-pose',
    name: 'Mountain Pose / Posture Check (Tadasana)',
    category: 'yoga',
    icon: '⛰️',
    mode: 'hold',
    camera: 'front',
    difficulty: 1,
    equipment: [],
    muscles: ['postural muscles', 'core', 'gluteus medius'],
    summary: 'Tall symmetric standing posture used as a frontal alignment check.',
    setup: [
      'Place the camera at chest height, facing you, 3 m away.',
      'Stand with feet together or hip-width.',
      'Arms by your sides, weight even on both feet.',
      'Stand tall and breathe steadily.',
    ],
    met: 2.3,
    angles: [
      { id: 'shoulders', label: 'Shoulder tilt', kind: 'segment', segment: 'shoulders', ref: 'horizontal' },
      { id: 'hips', label: 'Pelvic tilt', kind: 'segment', segment: 'hips', ref: 'horizontal' },
      { id: 'trunk', label: 'Trunk lean', kind: 'segment', segment: 'trunk', ref: 'vertical', side: 'both' },
      { id: 'knee', label: 'Knee alignment (valgus/varus)', kind: 'joint', joint: 'knee', side: 'both' },
      { id: 'stance', label: 'Stance width', kind: 'spread', what: 'feet' },
    ],
    hold: { targetSec: 30 },
    checks: [
      {
        angle: 'shoulders',
        when: 'hold',
        good: [0, 3],
        ok: [0, 6],
        cue: 'Level your shoulders',
        why: 'Persistent shoulder height asymmetry is a common postural screening flag.',
      },
      {
        angle: 'hips',
        when: 'hold',
        good: [0, 3],
        ok: [0, 6],
        cue: 'Balance weight on both feet',
        why: 'Pelvic obliquity in stance suggests uneven weight bearing or leg-length difference.',
      },
      {
        angle: 'trunk',
        when: 'hold',
        good: [0, 8],
        ok: [0, 12],
        cue: 'Stack ribs over pelvis',
        why: 'Lateral trunk shift loads one side of the spine asymmetrically.',
      },
      {
        angle: 'knee',
        when: 'hold',
        good: [172, 180],
        ok: [165, 180],
        cue: 'Keep knees over your feet',
        why: 'Front-on, this angle shows knock-knee or bow-leg alignment, not knee bend.',
      },
      {
        angle: 'stance',
        when: 'hold',
        good: [0.3, 0.8],
        ok: [0.15, 1.0],
        cue: 'Feet together to hip-width',
        why: 'AYUSH protocol Tadasana stands with feet about 2 inches apart, a narrow base that does not mask alignment faults.',
      },
    ],
  },

  // ─────────────────────────── Mobility ───────────────────────────
  {
    id: 'deep-squat-hold',
    name: 'Deep Squat Hold',
    category: 'mobility',
    icon: '🧎',
    mode: 'hold',
    camera: 'side',
    difficulty: 2,
    equipment: [],
    muscles: ['hip adductors', 'gluteus maximus', 'calves', 'ankles'],
    summary: 'Full-depth resting squat with heels down, testing hip and ankle mobility.',
    setup: [
      'Place the camera at hip height, side-on, 2–3 m away.',
      'Feet shoulder-width, toes slightly out.',
      'Sink as low as possible, heels flat.',
      'Keep chest lifted and hold.',
    ],
    met: 2.3,
    angles: [
      { id: 'knee', label: 'Knee angle', kind: 'joint', joint: 'knee', side: 'auto' },
      { id: 'hip', label: 'Hip angle', kind: 'joint', joint: 'hip', side: 'auto' },
      { id: 'trunk', label: 'Trunk inclination', kind: 'segment', segment: 'trunk', ref: 'vertical', side: 'auto' },
      { id: 'ankle', label: 'Ankle angle', kind: 'joint', joint: 'ankle', side: 'auto' },
    ],
    hold: { targetSec: 30 },
    checks: [
      {
        angle: 'knee',
        when: 'hold',
        good: [25, 60],
        ok: [20, 80],
        cue: 'Sink lower into the squat',
        why: 'Full squatting takes ~150°+ knee flexion (Hemmerich et al. 2006: 157 ± 6° heels-up); 80°+ here is only a parallel squat.',
        weight: 2,
      },
      {
        angle: 'hip',
        when: 'hold',
        good: [30, 70],
        ok: [20, 90],
        cue: 'Let hips drop below knees',
        why: 'Deep hip flexion reflects functional hip mobility.',
      },
      {
        angle: 'trunk',
        when: 'hold',
        good: [20, 50],
        ok: [10, 60],
        cue: 'Lift your chest',
        why: 'Excess forward lean usually compensates for limited ankle dorsiflexion.',
      },
      {
        angle: 'ankle',
        when: 'hold',
        good: [45, 75],
        ok: [35, 90],
        cue: 'Keep heels on the floor',
        why: 'Ankle dorsiflexion limits squat depth; heel lift increases knee load.',
      },
    ],
  },
  {
    id: 'overhead-reach-test',
    name: 'Overhead Reach (Shoulder Flexion Test)',
    category: 'mobility',
    icon: '🙆',
    mode: 'hold',
    camera: 'side',
    difficulty: 1,
    equipment: [],
    muscles: ['latissimus dorsi', 'deltoids', 'thoracic extensors'],
    summary: 'Standing arms-overhead reach measuring shoulder flexion without back arching.',
    setup: [
      'Place the camera at shoulder height, side-on, 2–3 m away.',
      'Stand tall, feet hip-width, ribs down.',
      'Raise straight arms as high overhead as possible.',
    ],
    met: 2.3,
    angles: [
      { id: 'shoulder', label: 'Shoulder flexion', kind: 'joint', joint: 'shoulder', side: 'auto' },
      { id: 'elbow', label: 'Elbow angle', kind: 'joint', joint: 'elbow', side: 'auto' },
      { id: 'trunk', label: 'Trunk inclination', kind: 'segment', segment: 'trunk', ref: 'vertical', side: 'auto' },
    ],
    hold: { targetSec: 5 },
    checks: [
      {
        angle: 'shoulder',
        when: 'hold',
        good: [160, 180],
        ok: [145, 180],
        cue: 'Reach arms back by your ears',
        why: 'AAOS norm is 180°; adults under 50 average ~160–170° active flexion (Gill et al. 2020).',
        weight: 2,
      },
      {
        angle: 'elbow',
        when: 'hold',
        good: [165, 180],
        ok: [150, 180],
        cue: 'Keep elbows straight',
        why: 'Bending the elbows hides restricted shoulder flexion.',
      },
      {
        angle: 'trunk',
        when: 'hold',
        good: [0, 8],
        ok: [0, 15],
        cue: 'Keep ribs down, don’t arch',
        why: 'Lumbar extension is the classic compensation for limited shoulder flexion.',
      },
    ],
  },
  {
    id: 'hip-hinge-drill',
    name: 'Hip Hinge Drill',
    category: 'mobility',
    icon: '🙇',
    mode: 'reps',
    camera: 'side',
    difficulty: 1,
    equipment: ['dowel (optional)'],
    muscles: ['hamstrings', 'gluteus maximus', 'erector spinae'],
    summary: 'Bodyweight hip hinge pattern drill: hips back, soft knees, vertical shins.',
    setup: [
      'Place the camera at hip height, side-on, 2–3 m away.',
      'Stand tall, feet hip-width, knees soft.',
      'Push hips back, torso tips forward, back flat.',
      'Squeeze glutes to return upright.',
    ],
    met: 2.8, // Compendium 2024 02024 calisthenics, light effort (unloaded drill)
    angles: [
      { id: 'hip', label: 'Hip angle', kind: 'joint', joint: 'hip', side: 'auto' },
      { id: 'knee', label: 'Knee angle', kind: 'joint', joint: 'knee', side: 'auto' },
      { id: 'shin', label: 'Shin inclination', kind: 'segment', segment: 'shin', ref: 'vertical', side: 'auto' },
    ],
    reps: { driver: 'hip', start: 'high', enter: 150, exit: 165, target: 115, minRepMs: 1000 },
    checks: [
      {
        angle: 'hip',
        when: 'bottom',
        good: [75, 115],
        ok: [65, 130],
        cue: 'Push hips further back',
        why: 'A hinge to a hip angle of about 75–115° (torso ~45° or lower) loads the hamstrings through range.',
      },
      {
        angle: 'hip',
        when: 'top',
        good: [172, 180],
        ok: [165, 180],
        cue: 'Stand fully tall, squeeze glutes',
        why: 'Finishing with full hip extension completes the hinge pattern.',
      },
      {
        angle: 'knee',
        when: 'active',
        good: [140, 170],
        ok: [125, 180],
        cue: 'Soft knees, don’t squat',
        why: 'Excess knee bend turns the hinge into a squat and unloads the hamstrings.',
      },
      {
        angle: 'shin',
        when: 'active',
        good: [0, 12],
        ok: [0, 20],
        cue: 'Keep shins vertical',
        why: 'Vertical shins are the hallmark of a hip-dominant hinge.',
      },
    ],
  },
  {
    id: 'standing-toe-touch',
    name: 'Standing Hamstring Toe-Touch Hold',
    category: 'mobility',
    icon: '🤸',
    mode: 'hold',
    camera: 'side',
    difficulty: 1,
    equipment: [],
    muscles: ['hamstrings', 'calves', 'erector spinae'],
    summary: 'Straight-legged standing forward fold reaching toward the toes.',
    setup: [
      'Place the camera at hip height, side-on, 2–3 m away.',
      'Stand with feet together, legs straight.',
      'Fold forward from the hips, reaching for toes.',
      'Relax the neck and hold.',
    ],
    met: 2.3,
    angles: [
      { id: 'hip', label: 'Hip angle', kind: 'joint', joint: 'hip', side: 'auto' },
      { id: 'knee', label: 'Knee angle', kind: 'joint', joint: 'knee', side: 'auto' },
      { id: 'elbow', label: 'Elbow angle', kind: 'joint', joint: 'elbow', side: 'auto' },
    ],
    hold: { targetSec: 20 },
    checks: [
      {
        angle: 'hip',
        when: 'hold',
        good: [20, 60],
        ok: [10, 80],
        cue: 'Fold deeper from the hips',
        why: 'Hand-to-foot pose combines ~83° hip and ~57° spinal flexion (Mullerpatan et al. 2019); avoid with back or disc problems (AYUSH).',
        weight: 2,
      },
      {
        angle: 'knee',
        when: 'hold',
        good: [165, 180],
        ok: [155, 180],
        cue: 'Keep knees straight',
        why: 'Bending the knees slackens the hamstrings and removes the stretch.',
      },
      {
        angle: 'elbow',
        when: 'hold',
        good: [160, 180],
        ok: [140, 180],
        cue: 'Let arms hang long',
        why: 'Straight arms show true reach and avoid pulling into the spine.',
      },
    ],
  },
  {
    id: 'knee-to-wall',
    name: 'Knee-to-Wall Ankle Dorsiflexion',
    category: 'mobility',
    icon: '🦶',
    mode: 'hold',
    camera: 'side',
    difficulty: 1,
    equipment: ['wall'],
    muscles: ['soleus', 'gastrocnemius', 'ankle joint'],
    summary: 'Lunge stance driving the front knee toward a wall with the heel down, testing ankle dorsiflexion.',
    setup: [
      'Place the camera at knee height, side-on, 2 m away.',
      'Face a wall, front foot nearer the camera.',
      'Drive the front knee forward over the toes.',
      'Keep the front heel flat and hold.',
    ],
    met: 2.3,
    angles: [
      { id: 'ankle', label: 'Ankle angle', kind: 'joint', joint: 'ankle', side: 'auto' },
      { id: 'shin', label: 'Shin inclination', kind: 'segment', segment: 'shin', ref: 'vertical', side: 'auto' },
      { id: 'trunk', label: 'Trunk inclination', kind: 'segment', segment: 'trunk', ref: 'vertical', side: 'auto' },
    ],
    hold: { targetSec: 5 },
    checks: [
      {
        angle: 'shin',
        when: 'hold',
        good: [35, 60],
        ok: [28, 65],
        cue: 'Drive knee further forward',
        why: 'Tibial inclination is the standard lunge-test dorsiflexion measure (Bennell et al. 1998, inter-rater ICC 0.97).',
        weight: 2,
      },
      {
        angle: 'ankle',
        when: 'hold',
        good: [45, 72],
        ok: [38, 78],
        cue: 'Keep your heel down',
        why: 'Neutral reads ~106° (toe landmark sits below the ankle); ~70° or less with heel flat is normal dorsiflexion.',
      },
      {
        angle: 'trunk',
        when: 'hold',
        good: [0, 20],
        ok: [0, 35],
        cue: 'Stay upright, hands on wall',
        why: 'Leaning in lets the hips move instead of the ankle.',
      },
    ],
  },
  {
    id: 'arm-circles',
    name: 'Arm Circles',
    category: 'mobility',
    icon: '🔄',
    mode: 'reps',
    camera: 'side',
    difficulty: 1,
    equipment: [],
    muscles: ['deltoids', 'rotator cuff', 'trapezius'],
    summary: 'Large straight-arm circles through full shoulder flexion as a warm-up.',
    setup: [
      'Place the camera at shoulder height, side-on, 2–3 m away.',
      'Stand tall, feet hip-width, arms by your sides.',
      'Sweep straight arms forward, up, back and down.',
    ],
    met: 2.8,
    angles: [
      { id: 'shoulder', label: 'Arm elevation', kind: 'joint', joint: 'shoulder', side: 'auto' },
      { id: 'elbow', label: 'Elbow angle', kind: 'joint', joint: 'elbow', side: 'auto' },
      { id: 'trunk', label: 'Trunk inclination', kind: 'segment', segment: 'trunk', ref: 'vertical', side: 'auto' },
    ],
    reps: { driver: 'shoulder', start: 'low', enter: 50, exit: 35, target: 160 },
    checks: [
      {
        angle: 'shoulder',
        when: 'bottom',
        good: [160, 180],
        ok: [140, 180],
        cue: 'Make bigger circles, reach overhead',
        why: 'Full-range circles move the shoulder through its whole flexion arc.',
      },
      {
        angle: 'shoulder',
        when: 'top',
        good: [0, 25],
        ok: [0, 35],
        cue: 'Bring arms all the way down',
        why: 'Completing the lower arc keeps each circle full-range.',
      },
      {
        angle: 'elbow',
        when: 'active',
        good: [160, 180],
        ok: [145, 180],
        cue: 'Keep arms long and straight',
        why: 'Straight arms maximise the moment arm and range of the circle.',
      },
      {
        angle: 'trunk',
        when: 'any',
        good: [0, 8],
        ok: [0, 15],
        cue: 'Keep torso still',
        why: 'Trunk sway substitutes for shoulder range.',
      },
    ],
  },
];
